import jsPDF from "jspdf";
import { format } from "date-fns";
import { fr } from "date-fns/locale";
import { formatCurrency as formatCurrencyUtil } from "./currency";

// ASCII-safe text (remove accents/emojis for jsPDF default fonts)
function sanitize(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\x20-\x7E]/g, "");
}

export interface DonationReceiptData {
  donation: {
    id: string;
    donation_date: string;
    donation_type: string;
    amount: number;
    payment_method: string;
    description: string | null;
    notes: string | null;
    reference_number?: string | null;
  };
  member: {
    first_name: string;
    last_name: string;
  } | null;
  churchInfo: {
    name: string;
    address: string;
    phone: string;
    email: string;
  };
  currencyCode: string;
  language: "fr" | "en" | "ht";
}

const translations = {
  fr: {
    title: "RECU DE DON",
    receiptNo: "Recu N",
    date: "Date",
    donor: "Donateur",
    anonymous: "Anonyme",
    type: "Type de don",
    amount: "Montant",
    paymentMethod: "Mode de paiement",
    description: "Description",
    certification: "Ce document certifie que le don ci-dessus a ete recu par",
    signature: "Signature autorisee",
    issueDate: "Date d'emission",
    generatedBy: "Document genere par Church Management Pro",
    typeLabels: { tithe: "Dime", offering: "Offrande", building: "Construction", mission: "Mission", special: "Don special", activity: "Activite", other: "Autre" },
    methodLabels: { cash: "Especes", check: "Cheque", transfer: "Virement", mobile_money: "Mobile Money", card: "Carte" },
  },
  en: {
    title: "DONATION RECEIPT",
    receiptNo: "Receipt No",
    date: "Date",
    donor: "Donor",
    anonymous: "Anonymous",
    type: "Donation Type",
    amount: "Amount",
    paymentMethod: "Payment Method",
    description: "Description",
    certification: "This document certifies that the above donation was received by",
    signature: "Authorized Signature",
    issueDate: "Issue Date",
    generatedBy: "Document generated by Church Management Pro",
    typeLabels: { tithe: "Tithe", offering: "Offering", building: "Building", mission: "Mission", special: "Special Gift", activity: "Activity", other: "Other" },
    methodLabels: { cash: "Cash", check: "Check", transfer: "Transfer", mobile_money: "Mobile Money", card: "Card" },
  },
  ht: {
    title: "RESI DON",
    receiptNo: "Resi N",
    date: "Dat",
    donor: "Done",
    anonymous: "Anonim",
    type: "Tip don",
    amount: "Montan",
    paymentMethod: "Metod peman",
    description: "Deskripsyon",
    certification: "Dokiman sa a sètifye ke don ki anwo a te resevwa pa",
    signature: "Siyati otorize",
    issueDate: "Dat emisyon",
    generatedBy: "Dokiman jenere pa Church Management Pro",
    typeLabels: { tithe: "Dim", offering: "Ofrann", building: "Konstriksyon", mission: "Misyon", special: "Don espesyal", activity: "Aktivite", other: "Lot" },
    methodLabels: { cash: "Kach", check: "Chek", transfer: "Viман", mobile_money: "Mobile Money", card: "Kat" },
  },
};

export function generateDonationReceiptPDF(data: DonationReceiptData): Blob {
  const t = translations[data.language] || translations.fr;
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  const primaryColor = [37, 99, 235] as const;
  const textColor = [31, 41, 55] as const;
  const mutedColor = [107, 114, 128] as const;

  let y = 0;

  // ========== HEADER ==========
  pdf.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  pdf.rect(0, 0, pageWidth, 45, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.text(sanitize(data.churchInfo.name), pageWidth / 2, 16, { align: "center" });

  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.text(sanitize(data.churchInfo.address), pageWidth / 2, 25, { align: "center" });
  pdf.text(sanitize(`Tel: ${data.churchInfo.phone} | Email: ${data.churchInfo.email}`), pageWidth / 2, 32, { align: "center" });

  y = 55;

  // ========== TITLE ==========
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text(sanitize(t.title), pageWidth / 2, y, { align: "center" });
  y += 8;

  // Receipt number
  const receiptId = data.donation.id.substring(0, 8).toUpperCase();
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text(sanitize(`${t.receiptNo}: ${receiptId}`), pageWidth / 2, y, { align: "center" });
  y += 15;

  // ========== DONATION DETAILS BOX ==========
  pdf.setFillColor(249, 250, 251);
  pdf.roundedRect(margin, y, contentWidth, 70, 3, 3, "F");

  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  const leftX = margin + 8;
  const valueX = margin + 55;
  let rowY = y + 10;

  const addRow = (label: string, value: string) => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.text(sanitize(label + ":"), leftX, rowY);
    pdf.setFont("helvetica", "normal");
    pdf.text(sanitize(value), valueX, rowY);
    rowY += 9;
  };

  const formattedDate = (() => {
    try { return format(new Date(data.donation.donation_date), "dd/MM/yyyy"); } catch { return data.donation.donation_date; }
  })();

  const donorName = data.member
    ? `${data.member.first_name} ${data.member.last_name}`
    : t.anonymous;

  const typeLabel = (t.typeLabels as Record<string, string>)[data.donation.donation_type] || data.donation.donation_type;
  const methodLabel = (t.methodLabels as Record<string, string>)[data.donation.payment_method] || data.donation.payment_method;
  const formattedAmount = formatCurrencyUtil(data.donation.amount, data.currencyCode);

  addRow(t.date, formattedDate);
  addRow(t.donor, donorName);
  addRow(t.type, typeLabel);
  addRow(t.paymentMethod, methodLabel);

  // Amount (larger, colored)
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(10);
  pdf.text(sanitize(t.amount + ":"), leftX, rowY);
  pdf.setFontSize(14);
  pdf.setTextColor(16, 185, 129);
  pdf.text(sanitize(formattedAmount), valueX, rowY);
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  rowY += 9;

  if (data.donation.description || data.donation.notes) {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.text(sanitize(t.description + ":"), leftX, rowY);
    pdf.setFont("helvetica", "normal");
    const desc = data.donation.description || data.donation.notes || "-";
    const truncated = desc.length > 60 ? desc.substring(0, 57) + "..." : desc;
    pdf.text(sanitize(truncated), valueX, rowY);
  }

  y += 80;

  // ========== CERTIFICATION ==========
  const certText = `${t.certification} ${data.churchInfo.name}.`;
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "italic");
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);

  const splitCert = pdf.splitTextToSize(sanitize(certText), contentWidth - 10);
  pdf.setFillColor(254, 243, 199);
  pdf.roundedRect(margin, y, contentWidth, splitCert.length * 5 + 10, 3, 3, "F");
  pdf.setTextColor(146, 64, 14);
  pdf.text(splitCert, margin + 5, y + 8);
  y += splitCert.length * 5 + 20;

  // ========== SIGNATURE ==========
  const signatureY = Math.max(y + 20, pageHeight - 50);
  pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);

  pdf.text(sanitize(`${t.issueDate}: ${format(new Date(), "dd/MM/yyyy")}`), margin, signatureY);
  pdf.text(sanitize(`${t.signature}: _____________________________`), margin + contentWidth / 2, signatureY);

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(mutedColor[0], mutedColor[1], mutedColor[2]);
  pdf.text(sanitize(t.generatedBy), pageWidth / 2, pageHeight - 10, { align: "center" });

  return pdf.output("blob");
}

export function downloadDonationReceiptPDF(blob: Blob, donationId: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `receipt_${donationId.substring(0, 8)}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
