project_id = "ihwhbtmnyhhceiwdcfsc"

[functions.send-welcome-email]
verify_jwt = true

[functions.send-absence-alert]
verify_jwt = true

[functions.send-expense-notification]
verify_jwt = true

[functions.send-birthday-notification]
verify_jwt = false

[functions.send-event-reminder]
verify_jwt = false

[functions.check-attendance-alerts]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = false

[functions.send-user-invite]
verify_jwt = false
