import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en" | "ht";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations: Record<Language, Record<string, any>> = {
  fr: {
    common: {
      save: "Enregistrer",
      cancel: "Annuler",
      delete: "Supprimer",
      edit: "Modifier",
      add: "Ajouter",
      search: "Rechercher",
      filter: "Filtrer",
      export: "Exporter",
      import: "Importer",
      loading: "Chargement...",
      noData: "Aucune donnée",
      actions: "Actions",
      status: "Statut",
      date: "Date",
      startDate: "Date de Début",
      endDate: "Date de Fin",
      name: "Nom",
      email: "Email",
      phone: "Téléphone",
      address: "Adresse",
      active: "Actif",
      inactive: "Inactif",
      transferred: "Transféré",
      all: "Tous",
      yes: "Oui",
      no: "Non",
      confirm: "Confirmer",
      close: "Fermer",
      print: "Imprimer",
      download: "Télécharger",
      welcome: "Bienvenue dans le système de gestion de votre église",
      total: "Total",
      group: "Groupe",
      joinedDate: "Date d'inscription",
      recentMembers: "Membres Récents",
      noRecentMembers: "Aucun nouveau membre ces 30 derniers jours",
      registeredOn: "Inscrit le",
      statisticsSummary: "Résumé Statistique",
      activeBranches: "Branches Actives",
      totalBranchesInSystem: "Total des branches dans le système",
      activeMinistries: "Ministères Actifs",
      totalMinistriesInChurch: "Total des ministères de l'église",
      baptismRate: "Taux de Baptême",
      baptizedMembers: "des membres baptisés",
      noBirthdayToday: "Pas d'anniversaire aujourd'hui",
      noBirthdayNextWeek: "Aucun anniversaire la semaine prochaine",
      happyBirthday: "Bon Fèt!",
    },
    nav: {
      dashboard: "Tableau de Bord",
      members: "Membres",
      memberCards: "Cartes Membres",
      attendance: "Présence",
      attendanceAlerts: "Alertes Présence",
      groupComparison: "Comparaison Groupes",
      donations: "Recettes",
      financialReports: "Rapports Financiers",
      events: "Événements",
      ministries: "Ministères",
      branches: "Branches",
      customFields: "Champs Personnalisés",
      logout: "Déconnexion",
    },
    dashboard: {
      title: "Tableau de Bord",
      totalMembers: "Total Membres",
      activeMembers: "Membres Actifs",
      totalBaptized: "Total Baptisés",
      totalMinistries: "Total Ministères",
      weeklyAttendance: "Présence Semaine",
      membersPresent: "membres présents",
      totalBranches: "Total Branches",
      activeBranches: "branches actives",
      monthlyOfferings: "Offrandes du Mois",
      totalDonations: "Total des Recettes",
      avgAttendance: "Présence Moyenne",
      recentActivity: "Activité Récente",
      upcomingBirthdays: "Anniversaires à venir",
      todayBirthdays: "Anniversaires du Jour",
      trends: "Tendances sur 6 mois",
      membersTrend: "Évolution des Membres",
      donationsTrend: "Évolution des Recettes",
      attendanceTrend: "Évolution de la Présence",
      newMembers: "Nouveaux Membres",
    },
    members: {
      title: "Gestion des Membres",
      subtitle: "Gérez les membres de votre église",
      addMember: "Ajouter un Membre",
      searchPlaceholder: "Rechercher un membre...",
      filterByStatus: "Filtrer par statut",
      filterByBranch: "Filtrer par branche",
      allStatuses: "Tous les statuts",
      allBranches: "Toutes les branches",
      firstName: "Prénom",
      lastName: "Nom",
      dateOfBirth: "Date de naissance",
      memberType: "Type de membre",
      role: "Rôle",
      branch: "Branche",
      viewDetails: "Voir les détails",
      noMembers: "Aucun membre trouvé",
    },
    attendance: {
      title: "Gestion des Présences",
      subtitle: "Enregistrez et suivez les présences",
      markAttendance: "Marquer la présence",
      scanQR: "Scanner QR Code",
      eventType: "Type d'événement",
      eventDate: "Date de l'événement",
      selectMember: "Sélectionner un membre",
      present: "Présent",
      absent: "Absent",
      recentScans: "Scans Récents",
      scanSuccess: "Présence enregistrée",
      scanError: "Erreur de scan",
      kioskMode: "Mode Kiosque",
      exitKiosk: "Quitter le mode kiosque",
      settings: "Paramètres du scanner",
      trackMemberAttendance: "Suivez la présence des membres à chaque réunion",
      closeScanner: "Fermer Scanner",
      openScanner: "Ouvrir Scanner",
      recordAttendance: "Enregistrer Présence",
      scanQrCode: "Scanner QR Code",
      clickFieldToScan: "Cliquez dans le champ ci-dessous et utilisez votre scanner externe pour scanner les QR codes des membres",
      scanField: "Champ de Scan (Cliquez pour focus)",
      scanQrHere: "Scannez le QR code ici...",
      scannerAutoType: "Le scanner externe tapera automatiquement le QR code dans ce champ. La présence sera marquée automatiquement.",
      lastScans: "Derniers Scans",
      success: "Succès",
      error: "Erreur",
      totalMembers: "Total Membres",
      activeMembers: "Membres actifs",
      lastMeeting: "Dernière Rencontre",
      noMeetings: "Pas de rencontres",
      averagePercentage: "Pourcentage Moyen",
      onAverage: "en moyenne",
      averageAttendance: "Présence Moyenne",
      vsPreviousPeriod: "vs période précédente",
      totalMeetings: "Total Rencontres",
      totalRecorded: "Total enregistré",
      highestAttendance: "Plus Haute Présence",
      recentAttendance: "Présence Récente",
      attendanceHistoryDescription: "Historique de présence pour les dernières rencontres",
      event: "Événement",
      date: "Date",
      totalPresent: "Total Présent",
      percentage: "Pourcentage",
      actions: "Actions",
      loading: "Chargement...",
      noAttendanceRecords: "Aucun enregistrement de présence.",
      statistics: "Statistiques",
      scanQrToMarkAttendance: "Scannez les QR codes des membres pour marquer leur présence",
      closeKioskMode: "Fermer Mode Kiosque",
      readyToScan: "Prêt à scanner",
      scanQrToStart: "Scannez les QR codes des membres pour commencer",
      attendanceMarked: "Présence Marquée!",
      totalScansToday: "Total Scans Aujourd'hui",
      errors: "Erreurs",
      successRate: "Taux de Réussite",
      memberNotFound: "Membre non trouvé",
      qrCodeNotFound: "Le QR code \"{qrCode}\" ne correspond à aucun membre actif",
      unknown: "Inconnu",
      alreadyMarked: "Déjà marqué",
      alreadyMarkedToday: "{name} a déjà été marqué présent aujourd'hui",
      memberMarkedPresent: "{name} a été marqué présent",
      attendanceRecordError: "Problème lors de l'enregistrement de la présence",
    },
    donations: {
      title: "Gestion des Recettes",
      subtitle: "Enregistrez et suivez les contributions",
      addDonation: "Enregistrer une Recette",
      amount: "Montant",
      donationType: "Type de recette",
      paymentMethod: "Méthode de paiement",
      donationDate: "Date de la recette",
      notes: "Notes",
      tithe: "Dîme",
      offering: "Offrande",
      mission: "Mission",
      building: "Construction",
      special: "Spécial",
      cash: "Espèces",
      check: "Chèque",
      transfer: "Virement",
      card: "Carte",
      other: "Autre",
      totalAmount: "Montant Total",
      avgDonation: "Recette Moyenne",
      donationCount: "Nombre de Recettes",
    },
    ministries: {
      title: "Gestion des Ministères",
      subtitle: "Gérez les ministères de votre église",
      addMinistry: "Ajouter un Ministère",
      ministryName: "Nom du ministère",
      description: "Description",
      leader: "Responsable",
      memberCount: "Nombre de membres",
      viewDetails: "Voir les détails",
      addMember: "Ajouter un membre",
      removeMember: "Retirer le membre",
    },
    branches: {
      title: "Gestion des Branches",
      subtitle: "Gérez les branches de votre église",
      addBranch: "Ajouter une Branche",
      branchName: "Nom de la branche",
      parentBranch: "Branche parente",
      orgChart: "Organigramme",
    },
    auth: {
      login: "Connexion",
      signup: "Inscription",
      email: "Email",
      password: "Mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      firstName: "Prénom",
      lastName: "Nom",
      loginButton: "Se connecter",
      signupButton: "S'inscrire",
      noAccount: "Pas de compte ?",
      hasAccount: "Déjà un compte ?",
      loginSuccess: "Connexion réussie",
      signupSuccess: "Inscription réussie",
      loginError: "Erreur de connexion",
      signupError: "Erreur d'inscription",
    },
    events: {
      title: "Gestion des Événements",
      subtitle: "Planifiez et gérez les événements",
      addEvent: "Ajouter un Événement",
      eventName: "Nom de l'événement",
      eventDate: "Date",
      eventTime: "Heure",
      location: "Lieu",
      description: "Description",
    },
    customFields: {
      title: "Champs Personnalisés",
      subtitle: "Configurez les champs additionnels",
      addField: "Ajouter un Champ",
      fieldName: "Nom du champ",
      fieldLabel: "Libellé",
      fieldType: "Type",
      entityType: "Type d'entité",
      required: "Obligatoire",
      options: "Options",
    },
    settings: {
      title: "Paramètres",
      language: "Langue",
      theme: "Thème",
      notifications: "Notifications",
      scannerSettings: "Paramètres du scanner",
      soundEnabled: "Son activé",
      volume: "Volume",
      successSound: "Son de succès",
      errorSound: "Son d'erreur",
    },
    errors: {
      required: "Ce champ est requis",
      invalidEmail: "Email invalide",
      passwordMismatch: "Les mots de passe ne correspondent pas",
      minLength: "Minimum {min} caractères",
      serverError: "Erreur serveur",
      notFound: "Non trouvé",
    },
  },
  en: {
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      search: "Search",
      filter: "Filter",
      export: "Export",
      import: "Import",
      loading: "Loading...",
      noData: "No data",
      actions: "Actions",
      status: "Status",
      date: "Date",
      startDate: "Start Date",
      endDate: "End Date",
      name: "Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      active: "Active",
      inactive: "Inactive",
      transferred: "Transferred",
      all: "All",
      yes: "Yes",
      no: "No",
      confirm: "Confirm",
      close: "Close",
      print: "Print",
      download: "Download",
      welcome: "Welcome to your church management system",
      total: "Total",
      group: "Group",
      joinedDate: "Joined Date",
      recentMembers: "Recent Members",
      noRecentMembers: "No new members in the last 30 days",
      registeredOn: "Registered on",
      statisticsSummary: "Statistics Summary",
      activeBranches: "Active Branches",
      totalBranchesInSystem: "Total branches in system",
      activeMinistries: "Active Ministries",
      totalMinistriesInChurch: "Total ministries in church",
      baptismRate: "Baptism Rate",
      baptizedMembers: "of members baptized",
      noBirthdayToday: "No birthday today",
      noBirthdayNextWeek: "No birthday next week",
      happyBirthday: "Happy Birthday!",
    },
    nav: {
      dashboard: "Dashboard",
      members: "Members",
      memberCards: "Member Cards",
      attendance: "Attendance",
      attendanceAlerts: "Attendance Alerts",
      groupComparison: "Group Comparison",
      donations: "Income",
      financialReports: "Financial Reports",
      events: "Events",
      ministries: "Ministries",
      branches: "Branches",
      customFields: "Custom Fields",
      logout: "Logout",
    },
    dashboard: {
      title: "Dashboard",
      totalMembers: "Total Members",
      activeMembers: "Active Members",
      totalBaptized: "Total Baptized",
      totalMinistries: "Total Ministries",
      weeklyAttendance: "Weekly Attendance",
      membersPresent: "members present",
      totalBranches: "Total Branches",
      activeBranches: "active branches",
      monthlyOfferings: "Monthly Offerings",
      totalDonations: "Total Income",
      avgAttendance: "Average Attendance",
      recentActivity: "Recent Activity",
      upcomingBirthdays: "Upcoming Birthdays",
      todayBirthdays: "Today's Birthdays",
      trends: "6-Month Trends",
      membersTrend: "Members Trend",
      donationsTrend: "Income Trend",
      attendanceTrend: "Attendance Trend",
      newMembers: "New Members",
    },
    members: {
      title: "Member Management",
      subtitle: "Manage your church members",
      addMember: "Add Member",
      searchPlaceholder: "Search a member...",
      filterByStatus: "Filter by status",
      filterByBranch: "Filter by branch",
      allStatuses: "All statuses",
      allBranches: "All branches",
      firstName: "First Name",
      lastName: "Last Name",
      dateOfBirth: "Date of Birth",
      memberType: "Member Type",
      role: "Role",
      branch: "Branch",
      viewDetails: "View Details",
      noMembers: "No members found",
    },
    attendance: {
      title: "Attendance Management",
      subtitle: "Record and track attendance",
      markAttendance: "Mark Attendance",
      scanQR: "Scan QR Code",
      eventType: "Event Type",
      eventDate: "Event Date",
      selectMember: "Select a member",
      present: "Present",
      absent: "Absent",
      recentScans: "Recent Scans",
      scanSuccess: "Attendance recorded",
      scanError: "Scan error",
      kioskMode: "Kiosk Mode",
      exitKiosk: "Exit kiosk mode",
      settings: "Scanner settings",
      trackMemberAttendance: "Track member attendance for each meeting",
      closeScanner: "Close Scanner",
      openScanner: "Open Scanner",
      recordAttendance: "Record Attendance",
      scanQrCode: "Scan QR Code",
      clickFieldToScan: "Click in the field below and use your external scanner to scan member QR codes",
      scanField: "Scan Field (Click to focus)",
      scanQrHere: "Scan QR code here...",
      scannerAutoType: "The external scanner will automatically type the QR code in this field. Attendance will be marked automatically.",
      lastScans: "Last Scans",
      success: "Success",
      error: "Error",
      totalMembers: "Total Members",
      activeMembers: "Active members",
      lastMeeting: "Last Meeting",
      noMeetings: "No meetings",
      averagePercentage: "Average Percentage",
      onAverage: "on average",
      averageAttendance: "Average Attendance",
      vsPreviousPeriod: "vs previous period",
      totalMeetings: "Total Meetings",
      totalRecorded: "Total recorded",
      highestAttendance: "Highest Attendance",
      recentAttendance: "Recent Attendance",
      attendanceHistoryDescription: "Attendance history for recent meetings",
      event: "Event",
      date: "Date",
      totalPresent: "Total Present",
      percentage: "Percentage",
      actions: "Actions",
      loading: "Loading...",
      noAttendanceRecords: "No attendance records yet.",
      statistics: "Statistics",
      scanQrToMarkAttendance: "Scan member QR codes to mark their attendance",
      closeKioskMode: "Close Kiosk Mode",
      readyToScan: "Ready to scan",
      scanQrToStart: "Scan member QR codes to start",
      attendanceMarked: "Attendance Marked!",
      totalScansToday: "Total Scans Today",
      errors: "Errors",
      successRate: "Success Rate",
      memberNotFound: "Member not found",
      qrCodeNotFound: "QR code \"{qrCode}\" does not match any active member",
      unknown: "Unknown",
      alreadyMarked: "Already marked",
      alreadyMarkedToday: "{name} has already been marked present today",
      memberMarkedPresent: "{name} has been marked present",
      attendanceRecordError: "Problem recording attendance",
    },
    donations: {
      title: "Income Management",
      subtitle: "Record and track contributions",
      addDonation: "Add Income",
      amount: "Amount",
      donationType: "Income Type",
      paymentMethod: "Payment Method",
      donationDate: "Income Date",
      notes: "Notes",
      tithe: "Tithe",
      offering: "Offering",
      mission: "Mission",
      building: "Building",
      special: "Special",
      cash: "Cash",
      check: "Check",
      transfer: "Transfer",
      card: "Card",
      other: "Other",
      totalAmount: "Total Amount",
      avgDonation: "Average Income",
      donationCount: "Income Count",
    },
    ministries: {
      title: "Ministry Management",
      subtitle: "Manage your church ministries",
      addMinistry: "Add Ministry",
      ministryName: "Ministry Name",
      description: "Description",
      leader: "Leader",
      memberCount: "Member Count",
      viewDetails: "View Details",
      addMember: "Add Member",
      removeMember: "Remove Member",
    },
    branches: {
      title: "Branch Management",
      subtitle: "Manage your church branches",
      addBranch: "Add Branch",
      branchName: "Branch Name",
      parentBranch: "Parent Branch",
      orgChart: "Organization Chart",
    },
    auth: {
      login: "Login",
      signup: "Sign Up",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      firstName: "First Name",
      lastName: "Last Name",
      loginButton: "Log In",
      signupButton: "Sign Up",
      noAccount: "No account?",
      hasAccount: "Already have an account?",
      loginSuccess: "Login successful",
      signupSuccess: "Sign up successful",
      loginError: "Login error",
      signupError: "Sign up error",
    },
    events: {
      title: "Event Management",
      subtitle: "Plan and manage events",
      addEvent: "Add Event",
      eventName: "Event Name",
      eventDate: "Date",
      eventTime: "Time",
      location: "Location",
      description: "Description",
    },
    customFields: {
      title: "Custom Fields",
      subtitle: "Configure additional fields",
      addField: "Add Field",
      fieldName: "Field Name",
      fieldLabel: "Label",
      fieldType: "Type",
      entityType: "Entity Type",
      required: "Required",
      options: "Options",
    },
    settings: {
      title: "Settings",
      language: "Language",
      theme: "Theme",
      notifications: "Notifications",
      scannerSettings: "Scanner Settings",
      soundEnabled: "Sound Enabled",
      volume: "Volume",
      successSound: "Success Sound",
      errorSound: "Error Sound",
    },
    errors: {
      required: "This field is required",
      invalidEmail: "Invalid email",
      passwordMismatch: "Passwords do not match",
      minLength: "Minimum {min} characters",
      serverError: "Server error",
      notFound: "Not found",
    },
  },
  ht: {
    common: {
      save: "Anrejistre",
      cancel: "Anile",
      delete: "Efase",
      edit: "Modifye",
      add: "Ajoute",
      search: "Chèche",
      filter: "Filtre",
      export: "Ekspòte",
      import: "Enpòte",
      loading: "Ap chaje...",
      noData: "Pa gen done",
      actions: "Aksyon",
      status: "Estati",
      date: "Dat",
      startDate: "Dat Kòmanse",
      endDate: "Dat Fini",
      name: "Non",
      email: "Imèl",
      phone: "Telefòn",
      address: "Adrès",
      active: "Aktif",
      inactive: "Inaktif",
      transferred: "Transfère",
      all: "Tout",
      yes: "Wi",
      no: "Non",
      confirm: "Konfime",
      close: "Fèmen",
      print: "Enprime",
      download: "Telechaje",
      welcome: "Byenveni nan sistèm jesyon legliz ou a",
      total: "Total",
      group: "Gwoup",
      joinedDate: "Dat enskripsyon",
      recentMembers: "Manm Resan",
      noRecentMembers: "Pa gen nouvo manm nan 30 dènye jou yo",
      registeredOn: "Enskri nan",
      statisticsSummary: "Rezime Estatistik",
      activeBranches: "Branch Aktif",
      totalBranchesInSystem: "Total branch nan sistèm nan",
      activeMinistries: "Ministè Aktif",
      totalMinistriesInChurch: "Total ministè legliz la",
      baptismRate: "To Batèm",
      baptizedMembers: "manm batize",
      noBirthdayToday: "Pa gen anivèsè jodi a",
      noBirthdayNextWeek: "Pa gen anivèsè semèn pwochèn",
      happyBirthday: "Bon Fèt!",
    },
    nav: {
      dashboard: "Tablo Debò",
      members: "Manm",
      memberCards: "Kat Manm",
      attendance: "Prezans",
      attendanceAlerts: "Alèt Prezans",
      groupComparison: "Konparezon Gwoup",
      donations: "Resèt",
      financialReports: "Rapò Finans",
      events: "Evènman",
      ministries: "Ministè",
      branches: "Branch",
      customFields: "Chan Pèsonalize",
      logout: "Dekonekte",
    },
    dashboard: {
      title: "Tablo Debò",
      totalMembers: "Total Manm",
      activeMembers: "Manm Aktif",
      totalBaptized: "Total Batize",
      totalMinistries: "Total Ministè",
      weeklyAttendance: "Prezans Semèn",
      membersPresent: "manm prezan",
      totalBranches: "Total Branch",
      activeBranches: "branch aktif",
      monthlyOfferings: "Ofrann Mwa a",
      totalDonations: "Total Resèt",
      avgAttendance: "Prezans Mwayèn",
      recentActivity: "Aktivite Resan",
      upcomingBirthdays: "Anivèsè k ap Vini",
      todayBirthdays: "Anivèsè Jodi a",
      trends: "Tandans sou 6 mwa",
      membersTrend: "Evolisyon Manm",
      donationsTrend: "Evolisyon Resèt",
      attendanceTrend: "Evolisyon Prezans",
      newMembers: "Nouvo Manm",
    },
    members: {
      title: "Jesyon Manm",
      subtitle: "Jere manm legliz ou yo",
      addMember: "Ajoute yon Manm",
      searchPlaceholder: "Chèche yon manm...",
      filterByStatus: "Filtre pa estati",
      filterByBranch: "Filtre pa branch",
      allStatuses: "Tout estati yo",
      allBranches: "Tout branch yo",
      firstName: "Prenon",
      lastName: "Non",
      dateOfBirth: "Dat nesans",
      memberType: "Tip manm",
      role: "Wòl",
      branch: "Branch",
      viewDetails: "Wè detay",
      noMembers: "Pa jwenn okenn manm",
    },
    attendance: {
      title: "Jesyon Prezans",
      subtitle: "Anrejistre ak swiv prezans",
      markAttendance: "Make prezans",
      scanQR: "Eskane kòd QR",
      eventType: "Tip evènman",
      eventDate: "Dat evènman",
      selectMember: "Chwazi yon manm",
      present: "Prezan",
      absent: "Absan",
      recentScans: "Eskanaj Resan",
      scanSuccess: "Prezans anrejistre",
      scanError: "Erè eskanaj",
      kioskMode: "Mòd Kyòsk",
      exitKiosk: "Kite mòd kyòsk",
      settings: "Paramèt eskanè",
      trackMemberAttendance: "Swiv prezans manm yo pou chak reyinyon",
      closeScanner: "Fèmen Eskanè",
      openScanner: "Ouvri Eskanè",
      recordAttendance: "Anrejistre Prezans",
      scanQrCode: "Eskane Kòd QR",
      clickFieldToScan: "Klike nan chan anba a epi itilize eskanè ekstèn ou pou eskane kòd QR manm yo",
      scanField: "Chan Eskanaj (Klike pou fokis)",
      scanQrHere: "Eskane kòd QR isit la...",
      scannerAutoType: "Eskanè ekstèn nan ap tape kòd QR la otomatikman nan chan sa. Prezans ap make otomatikman.",
      lastScans: "Dènye Eskanaj",
      success: "Siksè",
      error: "Erè",
      totalMembers: "Total Manm",
      activeMembers: "Manm aktif",
      lastMeeting: "Dènye Reyinyon",
      noMeetings: "Pa gen reyinyon",
      averagePercentage: "Pousantaj Mwayèn",
      onAverage: "an mwayèn",
      averageAttendance: "Prezans Mwayèn",
      vsPreviousPeriod: "vs peryòd pase",
      totalMeetings: "Total Reyinyon",
      totalRecorded: "Total anrejistre",
      highestAttendance: "Pi Gwo Prezans",
      recentAttendance: "Prezans Resan",
      attendanceHistoryDescription: "Istwa prezans pou dènye reyinyon yo",
      event: "Evènman",
      date: "Dat",
      totalPresent: "Total Prezan",
      percentage: "Pousantaj",
      actions: "Aksyon",
      loading: "Ap chaje...",
      noAttendanceRecords: "Pa gen anrejistreman prezans ankò.",
      statistics: "Estatistik",
      scanQrToMarkAttendance: "Eskane kòd QR manm yo pou make prezans yo",
      closeKioskMode: "Fèmen Mòd Kyòsk",
      readyToScan: "Prè pou eskane",
      scanQrToStart: "Eskane kòd QR manm yo pou kòmanse",
      attendanceMarked: "Prezans Make!",
      totalScansToday: "Total Eskanaj Jodi a",
      errors: "Erè",
      successRate: "To Siksè",
      memberNotFound: "Manm pa jwenn",
      qrCodeNotFound: "Kòd QR \"{qrCode}\" pa koresponn ak okenn manm aktif",
      unknown: "Enkoni",
      alreadyMarked: "Deja make",
      alreadyMarkedToday: "{name} deja make prezan jodi a",
      memberMarkedPresent: "{name} make prezan",
      attendanceRecordError: "Pwoblèm pandan anrejistreman prezans",
    },
    donations: {
      title: "Jesyon Resèt",
      subtitle: "Anrejistre ak swiv kontribisyon yo",
      addDonation: "Anrejistre yon Resèt",
      amount: "Montan",
      donationType: "Tip resèt",
      paymentMethod: "Metòd peman",
      donationDate: "Dat resèt",
      notes: "Nòt",
      tithe: "Ladim",
      offering: "Ofrann",
      mission: "Misyon",
      building: "Konstriksyon",
      special: "Espesyal",
      cash: "Kach",
      check: "Chèk",
      transfer: "Transfè",
      card: "Kat",
      other: "Lòt",
      totalAmount: "Montan Total",
      avgDonation: "Resèt Mwayèn",
      donationCount: "Kantite Resèt",
    },
    ministries: {
      title: "Jesyon Ministè",
      subtitle: "Jere ministè legliz ou yo",
      addMinistry: "Ajoute yon Ministè",
      ministryName: "Non ministè",
      description: "Deskripsyon",
      leader: "Responsab",
      memberCount: "Kantite manm",
      viewDetails: "Wè detay",
      addMember: "Ajoute yon manm",
      removeMember: "Retire manm nan",
    },
    branches: {
      title: "Jesyon Branch",
      subtitle: "Jere branch legliz ou yo",
      addBranch: "Ajoute yon Branch",
      branchName: "Non branch",
      parentBranch: "Branch paran",
      orgChart: "Òganigramm",
    },
    auth: {
      login: "Koneksyon",
      signup: "Enskri",
      email: "Imèl",
      password: "Modpas",
      confirmPassword: "Konfime modpas",
      firstName: "Prenon",
      lastName: "Non",
      loginButton: "Konekte",
      signupButton: "Enskri",
      noAccount: "Pa gen kont?",
      hasAccount: "Deja gen yon kont?",
      loginSuccess: "Koneksyon reyisi",
      signupSuccess: "Enskripsyon reyisi",
      loginError: "Erè koneksyon",
      signupError: "Erè enskripsyon",
    },
    events: {
      title: "Jesyon Evènman",
      subtitle: "Planifye ak jere evènman yo",
      addEvent: "Ajoute yon Evènman",
      eventName: "Non evènman",
      eventDate: "Dat",
      eventTime: "Lè",
      location: "Kote",
      description: "Deskripsyon",
    },
    customFields: {
      title: "Chan Pèsonalize",
      subtitle: "Konfigire chan adisyonèl yo",
      addField: "Ajoute yon Chan",
      fieldName: "Non chan",
      fieldLabel: "Etikèt",
      fieldType: "Tip",
      entityType: "Tip antite",
      required: "Obligatwa",
      options: "Opsyon",
    },
    settings: {
      title: "Paramèt",
      language: "Lang",
      theme: "Tèm",
      notifications: "Notifikasyon",
      scannerSettings: "Paramèt eskanè",
      soundEnabled: "Son aktive",
      volume: "Volim",
      successSound: "Son siksè",
      errorSound: "Son erè",
    },
    errors: {
      required: "Chan sa obligatwa",
      invalidEmail: "Imèl envalid",
      passwordMismatch: "Modpas yo pa menm",
      minLength: "Minimòm {min} karaktè",
      serverError: "Erè sèvè",
      notFound: "Pa jwenn",
    },
  },
};
