import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en" | "ht";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations = {
  fr: {
    common: {
      save: "Enregistrer",
      cancel: "Annuler",
      delete: "Supprimer",
      edit: "Modifier",
      add: "Ajouter",
      search: "Rechercher",
      filter: "Filtrer",
      export: "Exporter",
      import: "Importer",
      loading: "Chargement...",
      noData: "Aucune donnée",
      actions: "Actions",
      status: "Statut",
      date: "Date",
      startDate: "Date de Début",
      endDate: "Date de Fin",
      name: "Nom",
      email: "Email",
      phone: "Téléphone",
      address: "Adresse",
      active: "Actif",
      inactive: "Inactif",
      transferred: "Transféré",
      all: "Tous",
      yes: "Oui",
      no: "Non",
      select: "Sélectionner",
      none: "Aucun",
      error: "Erreur",
      confirm: "Confirmer",
      close: "Fermer",
      print: "Imprimer",
      download: "Télécharger",
      welcome: "Bienvenue dans le système de gestion de votre église",
      total: "Total",
      group: "Groupe",
      joinedDate: "Date d'inscription",
      recentMembers: "Membres Récents",
      noRecentMembers: "Aucun nouveau membre ces 30 derniers jours",
      registeredOn: "Inscrit le",
      statisticsSummary: "Résumé Statistique",
      activeBranches: "Branches Actives",
      totalBranchesInSystem: "Total des branches dans le système",
      activeMinistries: "Ministères Actifs",
      totalMinistriesInChurch: "Total des ministères de l'église",
      baptismRate: "Taux de Baptême",
      baptizedMembers: "des membres baptisés",
      noBirthdayToday: "Pas d'anniversaire aujourd'hui",
      noBirthdayNextWeek: "Aucun anniversaire la semaine prochaine",
      happyBirthday: "Bon Fèt!",
      description: "Description",
      account: "Compte",
      creator: "Créateur",
      details: "Détails",
      type: "Type",
      system: "Système",
      user: "Utilisateur",
      notSpecified: "Non spécifié",
      view: "Voir",
      downloadReceipt: "Télécharger reçu",
      viewDetails: "Voir détails",
    },
    nav: {
      dashboard: "Tableau de Bord",
      members: "Membres",
      memberCards: "Cartes Membres",
      attendance: "Présence",
      attendanceAlerts: "Alertes Présence",
      groupComparison: "Comparaison Groupes",
      donations: "Recettes",
      financialReports: "Rapports Financiers",
      budgets: "Budgets",
      expenses: "Dépenses",
      bankReconciliation: "Rapprochement Bancaire",
      financialDashboard: "Tableau de Bord Financier",
      specialFunds: "Fonds Spéciaux",
      cashRegister: "Caisse",
      auditTrail: "Historique d'Audit",
      events: "Événements",
      ministries: "Ministères",
      branches: "Branches",
      customFields: "Champs Personnalisés",
      logout: "Déconnexion",
    },
    finance: {
      dashboard: "Tableau de Bord Financier",
      totalIncome: "Recettes du Mois",
      totalExpenses: "Dépenses du Mois",
      bankBalance: "Solde Bancaire",
      annualBudget: "Budget Annuel",
      netIncome: "Revenu Net du Mois",
      monthlyTrends: "Tendances Mensuelles (6 mois)",
      incomeByType: "Recettes par Type",
      expensesByCategory: "Dépenses par Catégorie",
      bankAccounts: "Comptes Bancaires",
      income: "Recettes",
      expenses: "Dépenses",
      vsLastMonth: "vs mois dernier",
      activeAccounts: "comptes actifs",
      activeBudgets: "budgets actifs",
      specialFunds: "Fonds Spéciaux",
      cashRegister: "Caisse Physique",
      auditTrail: "Historique d'Audit",
    },
    dashboard: {
      title: "Tableau de Bord",
      totalMembers: "Total Membres",
      activeMembers: "Membres Actifs",
      totalBaptized: "Total Baptisés",
      totalMinistries: "Total Ministères",
      weeklyAttendance: "Présence Semaine",
      membersPresent: "membres présents",
      totalBranches: "Total Branches",
      activeBranches: "branches actives",
      monthlyOfferings: "Offrandes du Mois",
      totalDonations: "Total des Recettes",
      avgAttendance: "Présence Moyenne",
      recentActivity: "Activité Récente",
      upcomingBirthdays: "Anniversaires à venir",
      todayBirthdays: "Anniversaires du Jour",
      trends: "Tendances sur 6 mois",
      membersTrend: "Évolution des Membres",
      donationsTrend: "Évolution des Recettes",
      attendanceTrend: "Évolution de la Présence",
      newMembers: "Nouveaux Membres",
    },
    members: {
      title: "Gestion des Membres",
      subtitle: "Gérez les membres de votre église",
      addMember: "Ajouter un Membre",
      editMember: "Modifier le Membre",
      memberAdded: "Membre ajouté avec succès",
      memberUpdated: "Membre modifié avec succès",
      searchPlaceholder: "Rechercher un membre...",
      filterByStatus: "Filtrer par statut",
      filterByBranch: "Filtrer par branche",
      allStatuses: "Tous les statuts",
      allBranches: "Toutes les branches",
      // Personal Info
      personalInfo: "Informations Personnelles",
      firstName: "Prénom",
      lastName: "Nom",
      gender: "Sexe",
      selectGender: "Sélectionner le sexe",
      male: "Masculin",
      female: "Féminin",
      dateOfBirth: "Date de naissance",
      emergencyPhone: "Contact d'urgence",
      emergencyContact: "Contact d'urgence",
      address: "Adresse",
      street: "Rue",
      city: "Ville",
      zipCode: "Code Postal",
      stateRegion: "Département/Région",
      country: "Pays",
      joinDate: "Date d'entrée dans l'église",
      selectBranch: "Sélectionner une branche",
      memberNumber: "N° Membre",
      // Spiritual Info
      spiritualInfo: "Informations Spirituelles",
      baptized: "Baptisé",
      baptismDate: "Date de baptême",
      originChurch: "Église d'origine",
      originChurchPlaceholder: "Nom de l'église précédente",
      ministryRole: "Ministère / Service",
      selectRole: "Sélectionner un rôle",
      conversionDate: "Date de conversion",
      christianExperience: "Expérience Chrétienne/Ministérielle",
      christianExperiencePlaceholder: "Service dans l'église, responsabilités, etc.",
      availableMinistries: "Ministères disponibles",
      ministriesNote: "Les ministères se gèrent depuis la fiche détails du membre",
      roles: {
        member: "Membre",
        deacon: "Diacre",
        elder: "Ancien",
        pastor: "Pasteur",
        secretary: "Secrétaire",
        treasurer: "Trésorier",
        worship: "Chantre",
        tech: "Technique",
      },
      // Family Info
      familyInfo: "Informations Familiales",
      maritalStatus: "État civil",
      selectMaritalStatus: "Sélectionner l'état civil",
      marital: {
        single: "Célibataire",
        married: "Marié(e)",
        divorced: "Divorcé(e)",
        widowed: "Veuf/Veuve",
      },
      spouseName: "Nom du conjoint(e)",
      spouseNamePlaceholder: "Nom de votre conjoint(e)",
      marriageDate: "Date de mariage",
      numberOfChildren: "Nombre d'enfants",
      childrenNames: "Noms des enfants",
      childrenNamesPlaceholder: "Noms des enfants (séparés par une virgule)",
      // QR Code
      qrCode: "QR Code du Membre",
      qrCodeDescription: "Imprimez ce QR code pour marquer la présence",
      downloadQrCode: "Télécharger le QR Code",
      // Other
      memberType: "Type de membre",
      role: "Rôle",
      branch: "Branche",
      viewDetails: "Voir les détails",
      noMembers: "Aucun membre trouvé",
    },
    memberCards: {
      title: "Cartes des Membres",
      cardsSelected: "cartes sélectionnées",
      filtered: "filtrés",
      total: "total",
      markAttendance: "Marquer Présence",
      downloadPdf: "Télécharger PDF",
      generating: "Génération...",
      print: "Imprimer",
      generatingPdf: "Génération du PDF en cours...",
      filtersAndSearch: "Filtres et Recherche",
      searchMember: "Rechercher un Membre",
      typeName: "Tapez un nom...",
      role: "Rôle",
      allRoles: "Tous les rôles",
      member: "Membre",
      deacon: "Diacre",
      elder: "Ancien",
      pastor: "Pasteur",
      leader: "Dirigeant",
      baptismStatus: "Statut Baptême",
      allStatuses: "Tous les statuts",
      baptized: "Baptisé",
      notBaptized: "Non Baptisé",
      selectAll: "Tout Sélectionner",
      deselectAll: "Tout Désélectionner",
      clearFilters: "Effacer les Filtres",
      memberCard: "Carte de Membre",
      bornOn: "Né(e) le:",
      notDefined: "Non défini",
      memberSince: "Membre depuis:",
      phone: "Tél:",
      activeMember: "Membre Actif",
      noActiveMembers: "Aucun membre actif",
      addMembersToCreate: "Ajoutez des membres pour créer leurs cartes",
      qrCodesCreated: "Codes QR créés !",
      qrCodesCreatedDesc: "codes QR ont été créés pour les membres.",
      noMemberSelected: "Aucun membre sélectionné",
      selectAtLeastOne: "Veuillez sélectionner au moins un membre pour télécharger les cartes.",
      generatingCards: "Génération en cours",
      creatingCards: "Création des cartes pour",
      membersText: "membres...",
      pdfGenerated: "PDF généré avec succès",
      cardsDownloaded: "carte(s) téléchargée(s).",
      errorGeneratingPdf: "Impossible de générer le PDF. Veuillez réessayer.",
      attendanceDialog: {
        title: "Marquer la Présence",
        description: "Marquer la présence pour",
        membersSelected: "membres sélectionnés",
        eventType: "Type d'Événement",
        chooseEvent: "Choisir un événement",
        sundayService: "Service du Dimanche",
        bibleStudy: "Étude Biblique",
        prayerMeeting: "Réunion de Prière",
        youthGroup: "Groupe Jeunesse",
        other: "Autre",
        date: "Date",
        cancel: "Annuler",
        saving: "Enregistrement...",
        confirm: "Confirmer",
        selectEvent: "Veuillez choisir le type d'événement et la date.",
        selectMember: "Veuillez sélectionner au moins un membre.",
        success: "Succès !",
        attendanceRecorded: "Présence de {count} membres enregistrée.",
        error: "Problème lors de l'enregistrement des présences.",
      },
      loading: "Chargement des membres...",
      generatingQr: "Génération des codes QR...",
    },
    memberStats: {
      last6Months: "Statistiques des 6 derniers mois",
      totalPresences: "Total présences",
      attendanceRate: "Taux de présence",
      thisMonth: "Ce mois",
      trend: "Tendance",
      monthlyEvolution: "Évolution mensuelle",
      byEventType: "Par type d'événement",
      presences: "présences",
      noAttendanceRecords: "Aucun enregistrement de présence",
    },
    attendance: {
      title: "Gestion des Présences",
      subtitle: "Enregistrez et suivez les présences",
      markAttendance: "Marquer la présence",
      scanQR: "Scanner QR Code",
      eventType: "Type d'événement",
      eventDate: "Date de l'événement",
      selectMember: "Sélectionner un membre",
      present: "Présent",
      absent: "Absent",
      recentScans: "Scans Récents",
      scanSuccess: "Présence enregistrée",
      scanError: "Erreur de scan",
      kioskMode: "Mode Kiosque",
      exitKiosk: "Quitter le mode kiosque",
      settings: "Paramètres du scanner",
      trackMemberAttendance: "Suivez la présence des membres à chaque réunion",
      closeScanner: "Fermer Scanner",
      openScanner: "Ouvrir Scanner",
      recordAttendance: "Enregistrer Présence",
      scanQrCode: "Scanner QR Code",
      clickFieldToScan: "Cliquez dans le champ ci-dessous et utilisez votre scanner externe pour scanner les QR codes des membres",
      scanField: "Champ de Scan (Cliquez pour focus)",
      scanQrHere: "Scannez le QR code ici...",
      scannerAutoType: "Le scanner externe tapera automatiquement le QR code dans ce champ. La présence sera marquée automatiquement.",
      lastScans: "Derniers Scans",
      success: "Succès",
      error: "Erreur",
      totalMembers: "Total Membres",
      activeMembers: "Membres actifs",
      lastMeeting: "Dernière Rencontre",
      noMeetings: "Pas de rencontres",
      averagePercentage: "Pourcentage Moyen",
      onAverage: "en moyenne",
      averageAttendance: "Présence Moyenne",
      vsPreviousPeriod: "vs période précédente",
      totalMeetings: "Total Rencontres",
      totalRecorded: "Total enregistré",
      highestAttendance: "Plus Haute Présence",
      recentAttendance: "Présence Récente",
      attendanceHistoryDescription: "Historique de présence pour les dernières rencontres",
      event: "Événement",
      date: "Date",
      totalPresent: "Total Présent",
      percentage: "Pourcentage",
      actions: "Actions",
      loading: "Chargement...",
      noAttendanceRecords: "Aucun enregistrement de présence.",
      statistics: "Statistiques",
      scanQrToMarkAttendance: "Scannez les QR codes des membres pour marquer leur présence",
      closeKioskMode: "Fermer Mode Kiosque",
      readyToScan: "Prêt à scanner",
      scanQrToStart: "Scannez les QR codes des membres pour commencer",
      attendanceMarked: "Présence Marquée!",
      totalScansToday: "Total Scans Aujourd'hui",
      errors: "Erreurs",
      successRate: "Taux de Réussite",
      memberNotFound: "Membre non trouvé",
      qrCodeNotFound: "Le QR code \"{qrCode}\" ne correspond à aucun membre actif",
      unknown: "Inconnu",
      alreadyMarked: "Code déjà scanné",
      alreadyMarkedToday: "{name} a déjà été scanné pour cet événement",
      alreadyMarkedForEvent: "{name} a déjà été scanné pour {event}",
      codeAlreadyScanned: "CODE DÉJÀ SCANNÉ",
      duplicateScan: "Ce membre a déjà été enregistré",
      memberMarkedPresent: "{name} a été marqué présent",
      attendanceRecordError: "Problème lors de l'enregistrement de la présence",
      startCamera: "Démarrer la caméra",
      stopCamera: "Arrêter la caméra",
      cameraScanner: "Scanner Caméra",
      externalScanner: "Scanner Externe",
      orUseCamera: "Ou utilisez la caméra de votre appareil",
    },
    donations: {
      title: "Gestion des Recettes",
      subtitle: "Enregistrez et suivez les contributions",
      addDonation: "Enregistrer une Recette",
      amount: "Montant",
      donationType: "Type de recette",
      paymentMethod: "Méthode de paiement",
      donationDate: "Date de la recette",
      notes: "Notes",
      tithe: "Dîme",
      offering: "Offrande",
      mission: "Mission",
      building: "Construction",
      special: "Spécial",
      cash: "Espèces",
      check: "Chèque",
      transfer: "Virement",
      card: "Carte",
      other: "Autre",
      totalAmount: "Montant Total",
      avgDonation: "Recette Moyenne",
      donationCount: "Nombre de Recettes",
      donationHistory: "Historique des Contributions",
      totalAllTime: "Total Global",
      last6MonthsTotal: "Total 6 Mois",
      numberOfDonations: "Nombre de Dons",
      noDonationsRecorded: "Aucune contribution enregistrée",
      recentDonations: "Dernières Contributions",
      distributionByType: "Distribution par Type",
      monthlyEvolution: "Évolution Mensuelle",
    },
    ministries: {
      title: "Gestion des Ministères",
      subtitle: "Gérez les ministères de votre église",
      addMinistry: "Ajouter un Ministère",
      ministryName: "Nom du ministère",
      description: "Description",
      leader: "Responsable",
      memberCount: "Nombre de membres",
      viewDetails: "Voir les détails",
      addMember: "Ajouter un membre",
      removeMember: "Retirer le membre",
    },
    branches: {
      title: "Gestion des Branches",
      subtitle: "Gérez les branches de votre église",
      addBranch: "Ajouter une Branche",
      branchName: "Nom de la branche",
      parentBranch: "Branche parente",
      orgChart: "Organigramme",
    },
    auth: {
      login: "Connexion",
      signup: "Inscription",
      email: "Email",
      password: "Mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      firstName: "Prénom",
      lastName: "Nom",
      loginButton: "Se connecter",
      signupButton: "S'inscrire",
      noAccount: "Pas de compte ?",
      hasAccount: "Déjà un compte ?",
      loginSuccess: "Connexion réussie",
      signupSuccess: "Inscription réussie",
      loginError: "Erreur de connexion",
      signupError: "Erreur d'inscription",
    },
    events: {
      title: "Gestion des Événements",
      subtitle: "Planifiez et gérez les événements de votre église",
      addEvent: "Créer Événement",
      eventName: "Nom de l'événement",
      eventDate: "Date",
      eventTime: "Heure",
      location: "Lieu",
      description: "Description",
      calendar: "Calendrier",
      selectDate: "Choisissez une date pour voir les événements",
      eventsOn: "Événements du",
      eventsCount: "événement(s)",
      noEventsOnDate: "Aucun événement à cette date",
      participantsExpected: "participants attendus",
      participants: "participants",
      allUpcoming: "Tous les Événements à Venir",
      scheduled: "programmé(s)",
      noUpcoming: "Aucun événement à venir. Cliquez sur \"Créer Événement\" pour en ajouter un.",
      confirmed: "Confirmé",
      planned: "Planifié",
      cancelled: "Annulé",
      completed: "Terminé",
    },
    financialReports: {
      title: "Rapports Financiers",
      subtitle: "Analyse détaillée des contributions",
      allBranches: "Toutes les branches",
      lastMonths: "derniers mois",
      totalPeriod: "Total Période",
      currentMonth: "Mois Actuel",
      previousMonth: "Mois Précédent",
      avgDonation: "Recette Moyenne",
      perDonation: "par recette",
      vsPreviousMonth: "vs mois précédent",
      monthlyTrend: "Évolution Mensuelle",
      totalContributions: "Total contributions par mois",
      categoryDistribution: "Distribution par Catégorie",
      summaryByType: "Résumé par type de recette",
      categoryComparison: "Comparaison Catégories par Mois",
      donationDistribution: "Distribution des recettes par catégorie chaque mois",
      detailedSummary: "Résumé Mensuel Détaillé",
      exactFigures: "Chiffres exacts par mois et catégorie",
      month: "Mois",
      amount: "Montant",
      percentage: "Pourcentage",
    },
    customFields: {
      title: "Champs Personnalisés",
      subtitle: "Configurez les champs additionnels",
      addField: "Ajouter un Champ",
      fieldName: "Nom du champ",
      fieldLabel: "Libellé",
      fieldType: "Type",
      entityType: "Type d'entité",
      required: "Obligatoire",
      options: "Options",
    },
    budget: {
      title: "Gestion du Budget",
      subtitle: "Planifiez et suivez vos budgets annuels",
      addBudget: "Ajouter un Budget",
      budgetName: "Nom du budget",
      fiscalYear: "Année fiscale",
      plannedAmount: "Montant prévu",
      category: "Catégorie",
      totalPlanned: "Total Prévu",
      totalSpent: "Total Dépensé",
      remaining: "Restant",
      available: "disponible",
      utilizationRate: "Taux d'Utilisation",
      expensesApproved: "dépenses approuvées",
      budgetDetails: "Détails des Budgets",
      noBudgets: "Aucun budget créé pour cette année",
      planned: "Prévu",
      spent: "Dépensé",
      progress: "Progression",
    },
    expense: {
      title: "Gestion des Dépenses",
      subtitle: "Enregistrez et approuvez les dépenses",
      addExpense: "Ajouter une Dépense",
      viewExpense: "Détails de la Dépense",
      description: "Description",
      vendor: "Bénéficiaire",
      referenceNumber: "N° Justificatif",
      selectCategory: "Sélectionner une catégorie",
      totalExpenses: "Total Dépenses",
      transactions: "transactions",
      pendingApproval: "En Attente d'Approbation",
      awaitingReview: "en attente de révision",
      approved: "Approuvé",
      confirmedExpenses: "dépenses confirmées",
      avgExpense: "Dépense Moyenne",
      perTransaction: "par transaction",
      expenseList: "Liste des Dépenses",
      noExpenses: "Aucune dépense enregistrée",
      created: "Dépense créée avec succès",
      pending: "En attente",
      rejected: "Rejeté",
    },
    bank: {
      title: "Rapprochement Bancaire",
      subtitle: "Gérez vos comptes et réconciliez les transactions",
      addAccount: "Ajouter un Compte",
      accountName: "Nom du compte",
      accountNumber: "Numéro de compte",
      bankName: "Nom de la banque",
      initialBalance: "Solde initial",
      accountCreated: "Compte créé avec succès",
      noAccounts: "Aucun compte bancaire créé",
      transactions: "Transactions",
      reconciliationStatus: "Statut de réconciliation",
      addTransaction: "Ajouter une Transaction",
      transactionType: "Type de transaction",
      income: "Entrée",
      expense: "Sortie",
      transactionCreated: "Transaction créée avec succès",
      totalIncome: "Total Entrées",
      totalExpense: "Total Sorties",
      reconciled: "Réconcilié",
      pending: "En attente",
      toReconcile: "À réconcilier",
      noTransactions: "Aucune transaction",
      reconcile: "Réconcilier",
      unreconcile: "Annuler réconciliation",
      notSpecified: "Non spécifié",
    },
    settings: {
      title: "Paramètres",
      language: "Langue",
      theme: "Thème",
      notifications: "Notifications",
      scannerSettings: "Paramètres du scanner",
      soundEnabled: "Son activé",
      volume: "Volume",
      successSound: "Son de succès",
      errorSound: "Son d'erreur",
    },
    errors: {
      required: "Ce champ est requis",
      invalidEmail: "Email invalide",
      passwordMismatch: "Les mots de passe ne correspondent pas",
      minLength: "Minimum {min} caractères",
      serverError: "Erreur serveur",
      notFound: "Non trouvé",
    },
    layout: {
      members: "Membres",
      finances: "Finances",
      reports: "Rapports",
      communication: "Communication",
      planning: "Planning",
      settings: "Paramètres",
      inventory: "Inventaire",
      administration: "Administration",
      incomeCategories: "Catégories Recettes",
      expenseCategories: "Catégories Dépenses",
      salaries: "Salaires",
      emailTemplates: "Modèles d'emails",
      churchInfo: "Infos Église",
      inventoryManagement: "Gestion Inventaire",
      churchUsers: "Utilisateurs Église",
      customization: "Personnalisation",
      exploreData: "Explorer Données",
      churchManagement: "Gestion Églises",
      adminInvitations: "Invitations Admin",
      userManagement: "Gestion Utilisateurs",
      smartInsights: "Insights Intelligents",
      comingSoon: "Bientôt",
      logoutSuccess: "Vous êtes déconnecté avec succès",
      logoutError: "Problème de déconnexion",
    },
    superAdmin: {
      dashboardTitle: "Dashboard Super Admin",
      dashboardSubtitle: "Vue d'ensemble de toutes les églises sur la plateforme",
      exportCsv: "Exporter CSV",
      manageChurches: "Gérer les églises",
      totalChurches: "Total Églises",
      registeredChurches: "Églises enregistrées",
      monthlyRevenue: "Revenus Mensuels",
      recurringRevenue: "Revenus récurrents",
      activeUsers: "Utilisateurs Actifs",
      approvedUsers: "Utilisateurs approuvés",
      activeSubscriptions: "Abonnements Actifs",
      inTrial: "en période d'essai",
      recentChurches: "Églises Récentes",
      noChurchRegistered: "Aucune église enregistrée",
      quickActions: "Actions Rapides",
      exploreChurchData: "Explorer les données d'une église",
      userManagement: "Gestion des utilisateurs",
      noDataToExport: "Aucune donnée à exporter",
      csvExported: "Export CSV téléchargé",
      // Tenant Management
      tenantManagement: "Gestion Multi-Tenant",
      tenantManagementDesc: "Gérez les églises et leurs abonnements",
      addChurch: "Ajouter Église",
      editChurch: "Modifier l'église",
      createChurch: "Créer l'église",
      saveChanges: "Enregistrer",
      churchName: "Nom de l'église",
      slug: "Slug (URL)",
      contactEmail: "Email de contact",
      contactPhone: "Téléphone",
      adminEmail: "Email administrateur",
      inviteFirstAdmin: "Inviter le premier administrateur",
      plan: "Plan",
      planBasic: "Basique",
      planStandard: "Standard",
      planPremium: "Premium",
      planEnterprise: "Entreprise",
      status: "Statut",
      statusActive: "Actif",
      statusTrial: "Essai",
      statusSuspended: "Suspendu",
      statusCancelled: "Annulé",
      trialDuration: "Durée d'essai",
      customDate: "Date personnalisée",
      days14: "14 jours",
      month1: "1 mois",
      months3: "3 mois",
      months6: "6 mois",
      year1: "1 an",
      // Stats
      monthlyRevenueShort: "Revenus/mois",
      active: "Actifs",
      trial: "Essais",
      // Table headers
      church: "Église",
      subscription: "Abonnement",
      adminStatus: "Admin",
      actions: "Actions",
      noAdmin: "Aucun admin",
      hasAdmin: "Admin configuré",
      trialExpired: "Essai expiré",
      trialExpiresIn: "Expire dans",
      daysLeft: "jours",
      inviteAdmin: "Inviter Admin",
      extendTrial: "Prolonger essai",
      viewDetails: "Voir détails",
      deleteChurch: "Supprimer",
      // Data Viewer
      dataViewerTitle: "Explorer les données d'une église",
      dataViewerSubtitle: "Vue en lecture seule des données des églises",
      adminMode: "Mode Administration",
      readOnlyView: "Vous visualisez les données en lecture seule.",
      selectChurch: "Sélectionner une église",
      chooseChurch: "Choisissez une église pour explorer ses données",
      selectChurchPlaceholder: "Sélectionner une église...",
      membersTab: "Membres",
      donationsTab: "Donations",
      eventsTab: "Événements",
      branchesCount: "Branches",
      dataOf: "Données de",
      exploreData: "Explorez les membres, donations et événements",
      name: "Nom",
      email: "Email",
      phone: "Téléphone",
      type: "Type",
      registeredOn: "Inscrit le",
      noMembersFound: "Aucun membre trouvé",
      amount: "Montant",
      payment: "Paiement",
      notes: "Notes",
      noDonationsFound: "Aucune donation trouvée",
      date: "Date",
      time: "Heure",
      location: "Lieu",
      noEventsFound: "Aucun événement trouvé",
      exportMembers: "Exporter les membres",
      exportDonations: "Exporter les donations",
      exportEvents: "Exporter les événements",
      noMembersToExport: "Aucun membre à exporter",
      noDonationsToExport: "Aucune donation à exporter",
      noEventsToExport: "Aucun événement à exporter",
      membersExported: "Export membres téléchargé",
      donationsExported: "Export donations téléchargé",
      eventsExported: "Export événements téléchargé",
      // Extend Trial
      extendTrialTitle: "Prolonger l'essai",
      extendTrialFor: "Prolonger l'essai pour",
      currentTrialEnd: "Fin actuelle de l'essai",
      newTrialEnd: "Nouvelle fin d'essai",
      extending: "Prolongation...",
      confirmExtend: "Confirmer",
      trialExtended: "Essai prolongé jusqu'au",
      // Audit
      auditHistory: "Historique d'Audit",
      noAuditLogs: "Aucun historique d'audit",
      trialExtendedAction: "Essai prolongé",
      // Requests
      pendingRequests: "Demandes en attente",
      // Churches list
      churchesList: "Liste des Églises",
      noChurches: "Aucune église enregistrée",
      // Toasts
      churchCreated: "Client créé avec succès",
      churchUpdated: "Client mis à jour avec succès",
      churchDeleted: "Client supprimé avec succès",
      inviteSent: "Invitation envoyée à",
      inviteError: "Invitation envoyée mais erreur lors de l'envoi de l'email",
      createError: "Erreur lors de la création",
      updateError: "Erreur lors de la mise à jour",
      deleteError: "Erreur lors de la suppression",
      extendError: "Erreur lors de la prolongation",
    },
  },
  en: {
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      search: "Search",
      filter: "Filter",
      export: "Export",
      import: "Import",
      loading: "Loading...",
      noData: "No data",
      actions: "Actions",
      status: "Status",
      date: "Date",
      startDate: "Start Date",
      endDate: "End Date",
      name: "Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      active: "Active",
      inactive: "Inactive",
      transferred: "Transferred",
      all: "All",
      yes: "Yes",
      no: "No",
      select: "Select",
      none: "None",
      error: "Error",
      confirm: "Confirm",
      close: "Close",
      print: "Print",
      download: "Download",
      welcome: "Welcome to your church management system",
      total: "Total",
      group: "Group",
      joinedDate: "Joined Date",
      recentMembers: "Recent Members",
      noRecentMembers: "No new members in the last 30 days",
      registeredOn: "Registered on",
      statisticsSummary: "Statistics Summary",
      activeBranches: "Active Branches",
      totalBranchesInSystem: "Total branches in system",
      activeMinistries: "Active Ministries",
      totalMinistriesInChurch: "Total ministries in church",
      baptismRate: "Baptism Rate",
      baptizedMembers: "of members baptized",
      noBirthdayToday: "No birthday today",
      noBirthdayNextWeek: "No birthday next week",
      happyBirthday: "Happy Birthday!",
      description: "Description",
      account: "Account",
      creator: "Creator",
      details: "Details",
      type: "Type",
      system: "System",
      user: "User",
      notSpecified: "Not specified",
      view: "View",
      downloadReceipt: "Download receipt",
      viewDetails: "View details",
    },
    nav: {
      dashboard: "Dashboard",
      members: "Members",
      memberCards: "Member Cards",
      attendance: "Attendance",
      attendanceAlerts: "Attendance Alerts",
      groupComparison: "Group Comparison",
      donations: "Income",
      financialReports: "Financial Reports",
      budgets: "Budgets",
      expenses: "Expenses",
      bankReconciliation: "Bank Reconciliation",
      financialDashboard: "Financial Dashboard",
      specialFunds: "Special Funds",
      cashRegister: "Cash Register",
      auditTrail: "Audit Trail",
      events: "Events",
      ministries: "Ministries",
      branches: "Branches",
      customFields: "Custom Fields",
      logout: "Logout",
    },
    finance: {
      dashboard: "Financial Dashboard",
      totalIncome: "Monthly Income",
      totalExpenses: "Monthly Expenses",
      bankBalance: "Bank Balance",
      annualBudget: "Annual Budget",
      netIncome: "Net Monthly Income",
      monthlyTrends: "Monthly Trends (6 months)",
      incomeByType: "Income by Type",
      expensesByCategory: "Expenses by Category",
      bankAccounts: "Bank Accounts",
      income: "Income",
      expenses: "Expenses",
      vsLastMonth: "vs last month",
      activeAccounts: "active accounts",
      activeBudgets: "active budgets",
      specialFunds: "Special Funds",
      cashRegister: "Cash Register",
      auditTrail: "Audit Trail",
    },
    dashboard: {
      title: "Dashboard",
      totalMembers: "Total Members",
      activeMembers: "Active Members",
      totalBaptized: "Total Baptized",
      totalMinistries: "Total Ministries",
      weeklyAttendance: "Weekly Attendance",
      membersPresent: "members present",
      totalBranches: "Total Branches",
      activeBranches: "active branches",
      monthlyOfferings: "Monthly Offerings",
      totalDonations: "Total Income",
      avgAttendance: "Average Attendance",
      recentActivity: "Recent Activity",
      upcomingBirthdays: "Upcoming Birthdays",
      todayBirthdays: "Today's Birthdays",
      trends: "6-Month Trends",
      membersTrend: "Members Trend",
      donationsTrend: "Income Trend",
      attendanceTrend: "Attendance Trend",
      newMembers: "New Members",
    },
    members: {
      title: "Member Management",
      subtitle: "Manage your church members",
      addMember: "Add Member",
      editMember: "Edit Member",
      memberAdded: "Member added successfully",
      memberUpdated: "Member updated successfully",
      searchPlaceholder: "Search a member...",
      filterByStatus: "Filter by status",
      filterByBranch: "Filter by branch",
      allStatuses: "All statuses",
      allBranches: "All branches",
      // Personal Info
      personalInfo: "Personal Information",
      firstName: "First Name",
      lastName: "Last Name",
      gender: "Gender",
      selectGender: "Select gender",
      male: "Male",
      female: "Female",
      dateOfBirth: "Date of Birth",
      emergencyPhone: "Emergency Contact",
      emergencyContact: "Emergency Contact",
      address: "Address",
      street: "Street",
      city: "City",
      zipCode: "Zip Code",
      stateRegion: "State/Region",
      country: "Country",
      joinDate: "Church Join Date",
      selectBranch: "Select a branch",
      memberNumber: "Member No.",
      // Spiritual Info
      spiritualInfo: "Spiritual Information",
      baptized: "Baptized",
      baptismDate: "Baptism Date",
      originChurch: "Origin Church",
      originChurchPlaceholder: "Previous church name",
      ministryRole: "Ministry / Service",
      selectRole: "Select a role",
      conversionDate: "Conversion Date",
      christianExperience: "Christian/Ministry Experience",
      christianExperiencePlaceholder: "Church service, responsibilities, etc.",
      availableMinistries: "Available Ministries",
      ministriesNote: "Ministries are managed from the member details page",
      roles: {
        member: "Member",
        deacon: "Deacon",
        elder: "Elder",
        pastor: "Pastor",
        secretary: "Secretary",
        treasurer: "Treasurer",
        worship: "Worship Leader",
        tech: "Tech",
      },
      // Family Info
      familyInfo: "Family Information",
      maritalStatus: "Marital Status",
      selectMaritalStatus: "Select marital status",
      marital: {
        single: "Single",
        married: "Married",
        divorced: "Divorced",
        widowed: "Widowed",
      },
      spouseName: "Spouse Name",
      spouseNamePlaceholder: "Your spouse's name",
      marriageDate: "Marriage Date",
      numberOfChildren: "Number of Children",
      childrenNames: "Children's Names",
      childrenNamesPlaceholder: "Children's names (separated by comma)",
      // QR Code
      qrCode: "Member QR Code",
      qrCodeDescription: "Print this QR code for attendance tracking",
      downloadQrCode: "Download QR Code",
      // Other
      memberType: "Member Type",
      role: "Role",
      branch: "Branch",
      viewDetails: "View Details",
      noMembers: "No members found",
    },
    memberCards: {
      title: "Member Cards",
      cardsSelected: "cards selected",
      filtered: "filtered",
      total: "total",
      markAttendance: "Mark Attendance",
      downloadPdf: "Download PDF",
      generating: "Generating...",
      print: "Print",
      generatingPdf: "Generating PDF...",
      filtersAndSearch: "Filters and Search",
      searchMember: "Search Member",
      typeName: "Type a name...",
      role: "Role",
      allRoles: "All roles",
      member: "Member",
      deacon: "Deacon",
      elder: "Elder",
      pastor: "Pastor",
      leader: "Leader",
      baptismStatus: "Baptism Status",
      allStatuses: "All statuses",
      baptized: "Baptized",
      notBaptized: "Not Baptized",
      selectAll: "Select All",
      deselectAll: "Deselect All",
      clearFilters: "Clear Filters",
      memberCard: "Member Card",
      bornOn: "Born on:",
      notDefined: "Not defined",
      memberSince: "Member since:",
      phone: "Phone:",
      activeMember: "Active Member",
      noActiveMembers: "No active members",
      addMembersToCreate: "Add members to create their cards",
      qrCodesCreated: "QR Codes created!",
      qrCodesCreatedDesc: "QR codes have been created for members.",
      noMemberSelected: "No member selected",
      selectAtLeastOne: "Please select at least one member to download the cards.",
      generatingCards: "Generating",
      creatingCards: "Creating cards for",
      membersText: "members...",
      pdfGenerated: "PDF generated successfully",
      cardsDownloaded: "card(s) downloaded.",
      errorGeneratingPdf: "Unable to generate PDF. Please try again.",
      attendanceDialog: {
        title: "Mark Attendance",
        description: "Mark attendance for",
        membersSelected: "selected members",
        eventType: "Event Type",
        chooseEvent: "Choose an event",
        sundayService: "Sunday Service",
        bibleStudy: "Bible Study",
        prayerMeeting: "Prayer Meeting",
        youthGroup: "Youth Group",
        other: "Other",
        date: "Date",
        cancel: "Cancel",
        saving: "Saving...",
        confirm: "Confirm",
        selectEvent: "Please choose the event type and date.",
        selectMember: "Please select at least one member.",
        success: "Success!",
        attendanceRecorded: "Attendance for {count} members recorded.",
        error: "Problem recording attendance.",
      },
      loading: "Loading members...",
      generatingQr: "Generating QR codes...",
    },
    memberStats: {
      last6Months: "Last 6 months statistics",
      totalPresences: "Total presences",
      attendanceRate: "Attendance rate",
      thisMonth: "This month",
      trend: "Trend",
      monthlyEvolution: "Monthly evolution",
      byEventType: "By event type",
      presences: "presences",
      noAttendanceRecords: "No attendance records",
    },
    attendance: {
      title: "Attendance Management",
      subtitle: "Record and track attendance",
      markAttendance: "Mark Attendance",
      scanQR: "Scan QR Code",
      eventType: "Event Type",
      eventDate: "Event Date",
      selectMember: "Select a member",
      present: "Present",
      absent: "Absent",
      recentScans: "Recent Scans",
      scanSuccess: "Attendance recorded",
      scanError: "Scan error",
      kioskMode: "Kiosk Mode",
      exitKiosk: "Exit kiosk mode",
      settings: "Scanner settings",
      trackMemberAttendance: "Track member attendance for each meeting",
      closeScanner: "Close Scanner",
      openScanner: "Open Scanner",
      recordAttendance: "Record Attendance",
      scanQrCode: "Scan QR Code",
      clickFieldToScan: "Click in the field below and use your external scanner to scan member QR codes",
      scanField: "Scan Field (Click to focus)",
      scanQrHere: "Scan QR code here...",
      scannerAutoType: "The external scanner will automatically type the QR code in this field. Attendance will be marked automatically.",
      lastScans: "Last Scans",
      success: "Success",
      error: "Error",
      totalMembers: "Total Members",
      activeMembers: "Active members",
      lastMeeting: "Last Meeting",
      noMeetings: "No meetings",
      averagePercentage: "Average Percentage",
      onAverage: "on average",
      averageAttendance: "Average Attendance",
      vsPreviousPeriod: "vs previous period",
      totalMeetings: "Total Meetings",
      totalRecorded: "Total recorded",
      highestAttendance: "Highest Attendance",
      recentAttendance: "Recent Attendance",
      attendanceHistoryDescription: "Attendance history for recent meetings",
      event: "Event",
      date: "Date",
      totalPresent: "Total Present",
      percentage: "Percentage",
      actions: "Actions",
      loading: "Loading...",
      noAttendanceRecords: "No attendance records yet.",
      statistics: "Statistics",
      scanQrToMarkAttendance: "Scan member QR codes to mark their attendance",
      closeKioskMode: "Close Kiosk Mode",
      readyToScan: "Ready to scan",
      scanQrToStart: "Scan member QR codes to start",
      attendanceMarked: "Attendance Marked!",
      totalScansToday: "Total Scans Today",
      errors: "Errors",
      successRate: "Success Rate",
      memberNotFound: "Member not found",
      qrCodeNotFound: "QR code \"{qrCode}\" does not match any active member",
      unknown: "Unknown",
      alreadyMarked: "Code already scanned",
      alreadyMarkedToday: "{name} has already been scanned for this event",
      alreadyMarkedForEvent: "{name} has already been scanned for {event}",
      codeAlreadyScanned: "CODE ALREADY SCANNED",
      duplicateScan: "This member has already been registered",
      memberMarkedPresent: "{name} has been marked present",
      attendanceRecordError: "Problem recording attendance",
      startCamera: "Start camera",
      stopCamera: "Stop camera",
      cameraScanner: "Camera Scanner",
      externalScanner: "External Scanner",
      orUseCamera: "Or use your device's camera",
    },
    donations: {
      title: "Income Management",
      subtitle: "Record and track contributions",
      addDonation: "Add Income",
      amount: "Amount",
      donationType: "Income Type",
      paymentMethod: "Payment Method",
      donationDate: "Income Date",
      notes: "Notes",
      tithe: "Tithe",
      offering: "Offering",
      mission: "Mission",
      building: "Building",
      special: "Special",
      cash: "Cash",
      check: "Check",
      transfer: "Transfer",
      card: "Card",
      other: "Other",
      totalAmount: "Total Amount",
      avgDonation: "Average Income",
      donationCount: "Income Count",
      donationHistory: "Contribution History",
      totalAllTime: "Total All Time",
      last6MonthsTotal: "Last 6 Months Total",
      numberOfDonations: "Number of Donations",
      noDonationsRecorded: "No contributions recorded",
      recentDonations: "Recent Contributions",
      distributionByType: "Distribution by Type",
      monthlyEvolution: "Monthly Evolution",
    },
    ministries: {
      title: "Ministry Management",
      subtitle: "Manage your church ministries",
      addMinistry: "Add Ministry",
      ministryName: "Ministry Name",
      description: "Description",
      leader: "Leader",
      memberCount: "Member Count",
      viewDetails: "View Details",
      addMember: "Add Member",
      removeMember: "Remove Member",
    },
    branches: {
      title: "Branch Management",
      subtitle: "Manage your church branches",
      addBranch: "Add Branch",
      branchName: "Branch Name",
      parentBranch: "Parent Branch",
      orgChart: "Organization Chart",
    },
    auth: {
      login: "Login",
      signup: "Sign Up",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      firstName: "First Name",
      lastName: "Last Name",
      loginButton: "Log In",
      signupButton: "Sign Up",
      noAccount: "No account?",
      hasAccount: "Already have an account?",
      loginSuccess: "Login successful",
      signupSuccess: "Sign up successful",
      loginError: "Login error",
      signupError: "Sign up error",
    },
    events: {
      title: "Event Management",
      subtitle: "Plan and manage your church events",
      addEvent: "Create Event",
      eventName: "Event Name",
      eventDate: "Date",
      eventTime: "Time",
      location: "Location",
      description: "Description",
      calendar: "Calendar",
      selectDate: "Select a date to view events",
      eventsOn: "Events on",
      eventsCount: "event(s)",
      noEventsOnDate: "No events on this date",
      participantsExpected: "expected participants",
      participants: "participants",
      allUpcoming: "All Upcoming Events",
      scheduled: "scheduled",
      noUpcoming: "No upcoming events. Click \"Create Event\" to add one.",
      confirmed: "Confirmed",
      planned: "Planned",
      cancelled: "Cancelled",
      completed: "Completed",
    },
    financialReports: {
      title: "Financial Reports",
      subtitle: "Detailed analysis of contributions",
      allBranches: "All branches",
      lastMonths: "last months",
      totalPeriod: "Total Period",
      currentMonth: "Current Month",
      previousMonth: "Previous Month",
      avgDonation: "Average Income",
      perDonation: "per income",
      vsPreviousMonth: "vs previous month",
      monthlyTrend: "Monthly Trend",
      totalContributions: "Total contributions per month",
      categoryDistribution: "Category Distribution",
      summaryByType: "Summary by income type",
      categoryComparison: "Category Comparison by Month",
      donationDistribution: "Income distribution by category each month",
      detailedSummary: "Detailed Monthly Summary",
      exactFigures: "Exact figures by month and category",
      month: "Month",
      amount: "Amount",
      percentage: "Percentage",
    },
    customFields: {
      title: "Custom Fields",
      subtitle: "Configure additional fields",
      addField: "Add Field",
      fieldName: "Field Name",
      fieldLabel: "Label",
      fieldType: "Type",
      entityType: "Entity Type",
      required: "Required",
      options: "Options",
    },
    budget: {
      title: "Budget Management",
      subtitle: "Plan and track your annual budgets",
      addBudget: "Add Budget",
      budgetName: "Budget Name",
      fiscalYear: "Fiscal Year",
      plannedAmount: "Planned Amount",
      category: "Category",
      totalPlanned: "Total Planned",
      totalSpent: "Total Spent",
      remaining: "Remaining",
      available: "available",
      utilizationRate: "Utilization Rate",
      expensesApproved: "approved expenses",
      budgetDetails: "Budget Details",
      noBudgets: "No budgets created for this year",
      planned: "Planned",
      spent: "Spent",
      progress: "Progress",
    },
    expense: {
      title: "Expense Management",
      subtitle: "Record and approve expenses",
      addExpense: "Add Expense",
      viewExpense: "Expense Details",
      description: "Description",
      vendor: "Beneficiary",
      referenceNumber: "Receipt No.",
      selectCategory: "Select a category",
      totalExpenses: "Total Expenses",
      transactions: "transactions",
      pendingApproval: "Pending Approval",
      awaitingReview: "awaiting review",
      approved: "Approved",
      confirmedExpenses: "confirmed expenses",
      avgExpense: "Average Expense",
      perTransaction: "per transaction",
      expenseList: "Expense List",
      noExpenses: "No expenses recorded",
      created: "Expense created successfully",
      pending: "Pending",
      rejected: "Rejected",
    },
    bank: {
      title: "Bank Reconciliation",
      subtitle: "Manage accounts and reconcile transactions",
      addAccount: "Add Account",
      accountName: "Account Name",
      accountNumber: "Account Number",
      bankName: "Bank Name",
      initialBalance: "Initial Balance",
      accountCreated: "Account created successfully",
      noAccounts: "No bank accounts created",
      transactions: "Transactions",
      reconciliationStatus: "Reconciliation status",
      addTransaction: "Add Transaction",
      transactionType: "Transaction Type",
      income: "Income",
      expense: "Expense",
      transactionCreated: "Transaction created successfully",
      totalIncome: "Total Income",
      totalExpense: "Total Expenses",
      reconciled: "Reconciled",
      pending: "Pending",
      toReconcile: "To Reconcile",
      noTransactions: "No transactions",
      reconcile: "Reconcile",
      unreconcile: "Unreconcile",
      notSpecified: "Not specified",
    },
    settings: {
      title: "Settings",
      language: "Language",
      theme: "Theme",
      notifications: "Notifications",
      scannerSettings: "Scanner Settings",
      soundEnabled: "Sound Enabled",
      volume: "Volume",
      successSound: "Success Sound",
      errorSound: "Error Sound",
    },
    errors: {
      required: "This field is required",
      invalidEmail: "Invalid email",
      passwordMismatch: "Passwords do not match",
      minLength: "Minimum {min} characters",
      serverError: "Server error",
      notFound: "Not found",
    },
    layout: {
      members: "Members",
      finances: "Finances",
      reports: "Reports",
      communication: "Communication",
      planning: "Planning",
      settings: "Settings",
      inventory: "Inventory",
      administration: "Administration",
      incomeCategories: "Income Categories",
      expenseCategories: "Expense Categories",
      salaries: "Salaries",
      emailTemplates: "Email Templates",
      churchInfo: "Church Info",
      inventoryManagement: "Inventory Management",
      churchUsers: "Church Users",
      customization: "Customization",
      exploreData: "Explore Data",
      churchManagement: "Church Management",
      adminInvitations: "Admin Invitations",
      userManagement: "User Management",
      smartInsights: "Smart Insights",
      comingSoon: "Coming Soon",
      logoutSuccess: "You have been logged out successfully",
      logoutError: "Logout error",
    },
    superAdmin: {
      dashboardTitle: "Super Admin Dashboard",
      dashboardSubtitle: "Overview of all churches on the platform",
      exportCsv: "Export CSV",
      manageChurches: "Manage Churches",
      totalChurches: "Total Churches",
      registeredChurches: "Registered churches",
      monthlyRevenue: "Monthly Revenue",
      recurringRevenue: "Recurring revenue",
      activeUsers: "Active Users",
      approvedUsers: "Approved users",
      activeSubscriptions: "Active Subscriptions",
      inTrial: "in trial period",
      recentChurches: "Recent Churches",
      noChurchRegistered: "No church registered",
      quickActions: "Quick Actions",
      exploreChurchData: "Explore church data",
      userManagement: "User Management",
      noDataToExport: "No data to export",
      csvExported: "CSV export downloaded",
      // Tenant Management
      tenantManagement: "Multi-Tenant Management",
      tenantManagementDesc: "Manage churches and their subscriptions",
      addChurch: "Add Church",
      editChurch: "Edit Church",
      createChurch: "Create Church",
      saveChanges: "Save",
      churchName: "Church Name",
      slug: "Slug (URL)",
      contactEmail: "Contact Email",
      contactPhone: "Phone",
      adminEmail: "Admin Email",
      inviteFirstAdmin: "Invite first administrator",
      plan: "Plan",
      planBasic: "Basic",
      planStandard: "Standard",
      planPremium: "Premium",
      planEnterprise: "Enterprise",
      status: "Status",
      statusActive: "Active",
      statusTrial: "Trial",
      statusSuspended: "Suspended",
      statusCancelled: "Cancelled",
      trialDuration: "Trial Duration",
      customDate: "Custom Date",
      days14: "14 days",
      month1: "1 month",
      months3: "3 months",
      months6: "6 months",
      year1: "1 year",
      // Stats
      monthlyRevenueShort: "Revenue/month",
      active: "Active",
      trial: "Trial",
      // Table headers
      church: "Church",
      subscription: "Subscription",
      adminStatus: "Admin",
      actions: "Actions",
      noAdmin: "No admin",
      hasAdmin: "Admin configured",
      trialExpired: "Trial expired",
      trialExpiresIn: "Expires in",
      daysLeft: "days",
      inviteAdmin: "Invite Admin",
      extendTrial: "Extend Trial",
      viewDetails: "View Details",
      deleteChurch: "Delete",
      // Data Viewer
      dataViewerTitle: "Explore Church Data",
      dataViewerSubtitle: "Read-only view of church data",
      adminMode: "Admin Mode",
      readOnlyView: "You are viewing data in read-only mode.",
      selectChurch: "Select a Church",
      chooseChurch: "Choose a church to explore its data",
      selectChurchPlaceholder: "Select a church...",
      membersTab: "Members",
      donationsTab: "Donations",
      eventsTab: "Events",
      branchesCount: "Branches",
      dataOf: "Data of",
      exploreData: "Explore members, donations and events",
      name: "Name",
      email: "Email",
      phone: "Phone",
      type: "Type",
      registeredOn: "Registered on",
      noMembersFound: "No members found",
      amount: "Amount",
      payment: "Payment",
      notes: "Notes",
      noDonationsFound: "No donations found",
      date: "Date",
      time: "Time",
      location: "Location",
      noEventsFound: "No events found",
      exportMembers: "Export Members",
      exportDonations: "Export Donations",
      exportEvents: "Export Events",
      noMembersToExport: "No members to export",
      noDonationsToExport: "No donations to export",
      noEventsToExport: "No events to export",
      membersExported: "Members export downloaded",
      donationsExported: "Donations export downloaded",
      eventsExported: "Events export downloaded",
      // Extend Trial
      extendTrialTitle: "Extend Trial",
      extendTrialFor: "Extend trial for",
      currentTrialEnd: "Current trial end",
      newTrialEnd: "New trial end",
      extending: "Extending...",
      confirmExtend: "Confirm",
      trialExtended: "Trial extended until",
      // Audit
      auditHistory: "Audit History",
      noAuditLogs: "No audit history",
      trialExtendedAction: "Trial extended",
      // Requests
      pendingRequests: "Pending Requests",
      // Churches list
      churchesList: "Churches List",
      noChurches: "No churches registered",
      // Toasts
      churchCreated: "Church created successfully",
      churchUpdated: "Church updated successfully",
      churchDeleted: "Church deleted successfully",
      inviteSent: "Invitation sent to",
      inviteError: "Invitation sent but error sending email",
      createError: "Error creating church",
      updateError: "Error updating church",
      deleteError: "Error deleting church",
      extendError: "Error extending trial",
    },
  },
  ht: {
    common: {
      save: "Anrejistre",
      cancel: "Anile",
      delete: "Efase",
      edit: "Modifye",
      add: "Ajoute",
      search: "Chèche",
      filter: "Filtre",
      export: "Ekspòte",
      import: "Enpòte",
      loading: "Ap chaje...",
      noData: "Pa gen done",
      actions: "Aksyon",
      status: "Estati",
      date: "Dat",
      startDate: "Dat Kòmanse",
      endDate: "Dat Fini",
      name: "Non",
      email: "Imèl",
      phone: "Telefòn",
      address: "Adrès",
      active: "Aktif",
      inactive: "Inaktif",
      transferred: "Transfère",
      all: "Tout",
      yes: "Wi",
      no: "Non",
      select: "Chwazi",
      none: "Okenn",
      error: "Erè",
      confirm: "Konfime",
      close: "Fèmen",
      print: "Enprime",
      download: "Telechaje",
      welcome: "Byenveni nan sistèm jesyon legliz ou a",
      total: "Total",
      group: "Gwoup",
      joinedDate: "Dat enskripsyon",
      recentMembers: "Manm Resan",
      noRecentMembers: "Pa gen nouvo manm nan 30 dènye jou yo",
      registeredOn: "Enskri nan",
      statisticsSummary: "Rezime Estatistik",
      activeBranches: "Branch Aktif",
      totalBranchesInSystem: "Total branch nan sistèm nan",
      activeMinistries: "Ministè Aktif",
      totalMinistriesInChurch: "Total ministè legliz la",
      baptismRate: "To Batèm",
      baptizedMembers: "manm batize",
      noBirthdayToday: "Pa gen anivèsè jodi a",
      noBirthdayNextWeek: "Pa gen anivèsè semèn pwochèn",
      happyBirthday: "Bon Fèt!",
      description: "Deskripsyon",
      account: "Kont",
      creator: "Kreyatè",
      details: "Detay",
      type: "Tip",
      system: "Sistèm",
      user: "Itilizatè",
      notSpecified: "Pa presize",
      view: "Wè",
      downloadReceipt: "Telechaje resi",
      viewDetails: "Wè detay",
    },
    nav: {
      dashboard: "Tablo Debò",
      members: "Manm",
      memberCards: "Kat Manm",
      attendance: "Prezans",
      attendanceAlerts: "Alèt Prezans",
      groupComparison: "Konparezon Gwoup",
      donations: "Resèt",
      financialReports: "Rapò Finans",
      budgets: "Bidjè",
      expenses: "Depans",
      bankReconciliation: "Rekonsilyasyon Bank",
      financialDashboard: "Tablo Debò Finans",
      specialFunds: "Fon Espesyal",
      cashRegister: "Kès",
      auditTrail: "Istwa Odit",
      events: "Evènman",
      ministries: "Ministè",
      branches: "Branch",
      customFields: "Chan Pèsonalize",
      logout: "Dekonekte",
    },
    finance: {
      dashboard: "Tablo Debò Finans",
      totalIncome: "Resèt Mwa a",
      totalExpenses: "Depans Mwa a",
      bankBalance: "Balans Bank",
      annualBudget: "Bidjè Anyèl",
      netIncome: "Revni Nèt Mwa a",
      monthlyTrends: "Tandans Mansyèl (6 mwa)",
      incomeByType: "Resèt pa Tip",
      expensesByCategory: "Depans pa Kategori",
      bankAccounts: "Kont Bank",
      income: "Resèt",
      expenses: "Depans",
      vsLastMonth: "vs mwa pase",
      activeAccounts: "kont aktif",
      activeBudgets: "bidjè aktif",
      specialFunds: "Fon Espesyal",
      cashRegister: "Kès Fizik",
      auditTrail: "Istwa Odit",
    },
    dashboard: {
      title: "Tablo Debò",
      totalMembers: "Total Manm",
      activeMembers: "Manm Aktif",
      totalBaptized: "Total Batize",
      totalMinistries: "Total Ministè",
      weeklyAttendance: "Prezans Semèn",
      membersPresent: "manm prezan",
      totalBranches: "Total Branch",
      activeBranches: "branch aktif",
      monthlyOfferings: "Ofrann Mwa a",
      totalDonations: "Total Resèt",
      avgAttendance: "Prezans Mwayèn",
      recentActivity: "Aktivite Resan",
      upcomingBirthdays: "Anivèsè k ap Vini",
      todayBirthdays: "Anivèsè Jodi a",
      trends: "Tandans sou 6 mwa",
      membersTrend: "Evolisyon Manm",
      donationsTrend: "Evolisyon Resèt",
      attendanceTrend: "Evolisyon Prezans",
      newMembers: "Nouvo Manm",
    },
    members: {
      title: "Jesyon Manm",
      subtitle: "Jere manm legliz ou yo",
      addMember: "Ajoute yon Manm",
      editMember: "Modifye Manm",
      memberAdded: "Manm ajoute avèk siksè",
      memberUpdated: "Manm modifye avèk siksè",
      searchPlaceholder: "Chèche yon manm...",
      filterByStatus: "Filtre pa estati",
      filterByBranch: "Filtre pa branch",
      allStatuses: "Tout estati yo",
      allBranches: "Tout branch yo",
      // Personal Info
      personalInfo: "Enfòmasyon Pèsonèl",
      firstName: "Prenon",
      lastName: "Non",
      gender: "Sèks",
      selectGender: "Chwazi sèks",
      male: "Gason",
      female: "Fi",
      dateOfBirth: "Dat nesans",
      emergencyPhone: "Kontak ijans",
      emergencyContact: "Kontak ijans",
      address: "Adrès",
      street: "Ri",
      city: "Vil",
      zipCode: "Kòd Postal",
      stateRegion: "Depatman/Rejyon",
      country: "Peyi",
      joinDate: "Dat antre nan legliz",
      selectBranch: "Chwazi yon branch",
      memberNumber: "N° Manm",
      // Spiritual Info
      spiritualInfo: "Enfòmasyon Espirityèl",
      baptized: "Batize",
      baptismDate: "Dat batèm",
      originChurch: "Legliz orijin",
      originChurchPlaceholder: "Non legliz anvan",
      ministryRole: "Ministè / Sèvis",
      selectRole: "Chwazi yon wòl",
      conversionDate: "Dat konvèsyon",
      christianExperience: "Eksperyans Kretyen/Ministè",
      christianExperiencePlaceholder: "Sèvis nan legliz, responsablite, elatriye.",
      availableMinistries: "Ministè disponib",
      ministriesNote: "Ministè yo jere nan paj detay manm nan",
      roles: {
        member: "Manm",
        deacon: "Dyak",
        elder: "Ansyen",
        pastor: "Pastè",
        secretary: "Sekretè",
        treasurer: "Trezorye",
        worship: "Chantè",
        tech: "Teknik",
      },
      // Family Info
      familyInfo: "Enfòmasyon Fanmi",
      maritalStatus: "Eta sivil",
      selectMaritalStatus: "Chwazi eta sivil",
      marital: {
        single: "Selibatè",
        married: "Marye",
        divorced: "Divòse",
        widowed: "Vèv/Vèf",
      },
      spouseName: "Non konjwen",
      spouseNamePlaceholder: "Non konjwen ou",
      marriageDate: "Dat maryaj",
      numberOfChildren: "Kantite timoun",
      childrenNames: "Non timoun yo",
      childrenNamesPlaceholder: "Non timoun yo (separe pa vigil)",
      // QR Code
      qrCode: "Kòd QR Manm",
      qrCodeDescription: "Enprime kòd QR sa a pou make prezans",
      downloadQrCode: "Telechaje Kòd QR",
      // Other
      memberType: "Tip manm",
      role: "Wòl",
      branch: "Branch",
      viewDetails: "Wè detay",
      noMembers: "Pa jwenn okenn manm",
    },
    memberCards: {
      title: "Kat Manm yo",
      cardsSelected: "kat chwazi",
      filtered: "filtre",
      total: "total",
      markAttendance: "Make Prezans",
      downloadPdf: "Telechaje PDF",
      generating: "Ap jenere...",
      print: "Enprime",
      generatingPdf: "Ap jenere PDF...",
      filtersAndSearch: "Filt ak Rechèch",
      searchMember: "Chèche Manm",
      typeName: "Tape yon non...",
      role: "Wòl",
      allRoles: "Tout wòl",
      member: "Manm",
      deacon: "Dyak",
      elder: "Ansyen",
      pastor: "Pastè",
      leader: "Lidè",
      baptismStatus: "Estati Batèm",
      allStatuses: "Tout estati",
      baptized: "Batize",
      notBaptized: "Pa Batize",
      selectAll: "Chwazi Tout",
      deselectAll: "Dechwazi Tout",
      clearFilters: "Efase Filt yo",
      memberCard: "Kat Manm",
      bornOn: "Fèt:",
      notDefined: "Pa defini",
      memberSince: "Manm depi:",
      phone: "Tel:",
      activeMember: "Manm Aktif",
      noActiveMembers: "Pa gen manm aktif",
      addMembersToCreate: "Ajoute manm pou kreye kat yo",
      qrCodesCreated: "Kòd QR kreye!",
      qrCodesCreatedDesc: "kòd QR te kreye pou manm yo.",
      noMemberSelected: "Okenn manm pa chwazi",
      selectAtLeastOne: "Tanpri chwazi omwen yon manm pou telechaje kat yo.",
      generatingCards: "Ap jenere",
      creatingCards: "Kreye kat pou",
      membersText: "manm...",
      pdfGenerated: "PDF jenere avèk siksè",
      cardsDownloaded: "kat telechaje.",
      errorGeneratingPdf: "Pa kapab jenere PDF. Tanpri eseye ankò.",
      attendanceDialog: {
        title: "Make Prezans",
        description: "Make prezans pou",
        membersSelected: "manm chwazi",
        eventType: "Tip Evènman",
        chooseEvent: "Chwazi yon evènman",
        sundayService: "Sèvis Dimanch",
        bibleStudy: "Etid Biblik",
        prayerMeeting: "Reyinyon Lapriyè",
        youthGroup: "Gwoup Jèn",
        other: "Lòt",
        date: "Dat",
        cancel: "Anile",
        saving: "Ap anrejistre...",
        confirm: "Konfime",
        selectEvent: "Tanpri chwazi tip evènman ak dat.",
        selectMember: "Tanpri chwazi omwen yon manm.",
        success: "Siksè!",
        attendanceRecorded: "Prezans pou {count} manm anrejistre.",
        error: "Pwoblèm pandan anrejistreman prezans.",
      },
      loading: "Ap chaje manm yo...",
      generatingQr: "Ap jenere kòd QR yo...",
    },
    memberStats: {
      last6Months: "Estatistik 6 dènye mwa yo",
      totalPresences: "Total prezans",
      attendanceRate: "To prezans",
      thisMonth: "Mwa sa a",
      trend: "Tandans",
      monthlyEvolution: "Evolisyon mansyèl",
      byEventType: "Pa tip evènman",
      presences: "prezans",
      noAttendanceRecords: "Pa gen okenn anrejistreman prezans",
    },
    attendance: {
      title: "Jesyon Prezans",
      subtitle: "Anrejistre ak swiv prezans",
      markAttendance: "Make prezans",
      scanQR: "Eskane kòd QR",
      eventType: "Tip evènman",
      eventDate: "Dat evènman",
      selectMember: "Chwazi yon manm",
      present: "Prezan",
      absent: "Absan",
      recentScans: "Eskanaj Resan",
      scanSuccess: "Prezans anrejistre",
      scanError: "Erè eskanaj",
      kioskMode: "Mòd Kyòsk",
      exitKiosk: "Kite mòd kyòsk",
      settings: "Paramèt eskanè",
      trackMemberAttendance: "Swiv prezans manm yo pou chak reyinyon",
      closeScanner: "Fèmen Eskanè",
      openScanner: "Ouvri Eskanè",
      recordAttendance: "Anrejistre Prezans",
      scanQrCode: "Eskane Kòd QR",
      clickFieldToScan: "Klike nan chan anba a epi itilize eskanè ekstèn ou pou eskane kòd QR manm yo",
      scanField: "Chan Eskanaj (Klike pou fokis)",
      scanQrHere: "Eskane kòd QR isit la...",
      scannerAutoType: "Eskanè ekstèn nan ap tape kòd QR la otomatikman nan chan sa. Prezans ap make otomatikman.",
      lastScans: "Dènye Eskanaj",
      success: "Siksè",
      error: "Erè",
      totalMembers: "Total Manm",
      activeMembers: "Manm aktif",
      lastMeeting: "Dènye Reyinyon",
      noMeetings: "Pa gen reyinyon",
      averagePercentage: "Pousantaj Mwayèn",
      onAverage: "an mwayèn",
      averageAttendance: "Prezans Mwayèn",
      vsPreviousPeriod: "vs peryòd pase",
      totalMeetings: "Total Reyinyon",
      totalRecorded: "Total anrejistre",
      highestAttendance: "Pi Gwo Prezans",
      recentAttendance: "Prezans Resan",
      attendanceHistoryDescription: "Istwa prezans pou dènye reyinyon yo",
      event: "Evènman",
      date: "Dat",
      totalPresent: "Total Prezan",
      percentage: "Pousantaj",
      actions: "Aksyon",
      loading: "Ap chaje...",
      noAttendanceRecords: "Pa gen anrejistreman prezans ankò.",
      statistics: "Estatistik",
      scanQrToMarkAttendance: "Eskane kòd QR manm yo pou make prezans yo",
      closeKioskMode: "Fèmen Mòd Kyòsk",
      readyToScan: "Prè pou eskane",
      scanQrToStart: "Eskane kòd QR manm yo pou kòmanse",
      attendanceMarked: "Prezans Make!",
      totalScansToday: "Total Eskanaj Jodi a",
      errors: "Erè",
      successRate: "To Siksè",
      memberNotFound: "Manm pa jwenn",
      qrCodeNotFound: "Kòd QR \"{qrCode}\" pa koresponn ak okenn manm aktif",
      unknown: "Enkoni",
      alreadyMarked: "Kòd deja eskane",
      alreadyMarkedToday: "{name} deja eskane pou evènman sa a",
      alreadyMarkedForEvent: "{name} deja eskane pou {event}",
      codeAlreadyScanned: "KÒD DEJA ESKANE",
      duplicateScan: "Manm sa a deja anrejistre",
      memberMarkedPresent: "{name} make prezan",
      attendanceRecordError: "Pwoblèm pandan anrejistreman prezans",
      startCamera: "Kòmanse kamera",
      stopCamera: "Sispann kamera",
      cameraScanner: "Eskanè Kamera",
      externalScanner: "Eskanè Ekstèn",
      orUseCamera: "Oswa itilize kamera aparèy ou a",
    },
    donations: {
      title: "Jesyon Resèt",
      subtitle: "Anrejistre ak swiv kontribisyon yo",
      addDonation: "Anrejistre yon Resèt",
      amount: "Montan",
      donationType: "Tip resèt",
      paymentMethod: "Metòd peman",
      donationDate: "Dat resèt",
      notes: "Nòt",
      tithe: "Ladim",
      offering: "Ofrann",
      mission: "Misyon",
      building: "Konstriksyon",
      special: "Espesyal",
      cash: "Kach",
      check: "Chèk",
      transfer: "Transfè",
      card: "Kat",
      other: "Lòt",
      totalAmount: "Montan Total",
      avgDonation: "Resèt Mwayèn",
      donationCount: "Kantite Resèt",
      donationHistory: "Istwa Kontribisyon",
      totalAllTime: "Total Tout Tan",
      last6MonthsTotal: "Total 6 Mwa",
      numberOfDonations: "Kantite Don",
      noDonationsRecorded: "Pa gen kontribisyon anrejistre",
      recentDonations: "Dènye Kontribisyon",
      distributionByType: "Distribisyon pa Tip",
      monthlyEvolution: "Evolisyon Mansyèl",
    },
    ministries: {
      title: "Jesyon Ministè",
      subtitle: "Jere ministè legliz ou yo",
      addMinistry: "Ajoute yon Ministè",
      ministryName: "Non ministè",
      description: "Deskripsyon",
      leader: "Responsab",
      memberCount: "Kantite manm",
      viewDetails: "Wè detay",
      addMember: "Ajoute yon manm",
      removeMember: "Retire manm nan",
    },
    branches: {
      title: "Jesyon Branch",
      subtitle: "Jere branch legliz ou yo",
      addBranch: "Ajoute yon Branch",
      branchName: "Non branch",
      parentBranch: "Branch paran",
      orgChart: "Òganigramm",
    },
    auth: {
      login: "Koneksyon",
      signup: "Enskri",
      email: "Imèl",
      password: "Modpas",
      confirmPassword: "Konfime modpas",
      firstName: "Prenon",
      lastName: "Non",
      loginButton: "Konekte",
      signupButton: "Enskri",
      noAccount: "Pa gen kont?",
      hasAccount: "Deja gen yon kont?",
      loginSuccess: "Koneksyon reyisi",
      signupSuccess: "Enskripsyon reyisi",
      loginError: "Erè koneksyon",
      signupError: "Erè enskripsyon",
    },
    events: {
      title: "Jesyon Evènman",
      subtitle: "Planifye ak jere evènman legliz ou yo",
      addEvent: "Kreye Evènman",
      eventName: "Non evènman",
      eventDate: "Dat",
      eventTime: "Lè",
      location: "Kote",
      description: "Deskripsyon",
      calendar: "Kalandriye",
      selectDate: "Chwazi yon dat pou wè evènman yo",
      eventsOn: "Evènman nan",
      eventsCount: "evènman",
      noEventsOnDate: "Pa gen evènman nan dat sa",
      participantsExpected: "patisipan espere",
      participants: "patisipan",
      allUpcoming: "Tout Evènman k ap Vini",
      scheduled: "pwograme",
      noUpcoming: "Pa gen evènman k ap vini. Klike sou \"Kreye Evènman\" pou ajoute youn.",
      confirmed: "Konfime",
      planned: "Planifye",
      cancelled: "Anile",
      completed: "Fini",
    },
    financialReports: {
      title: "Rapò Finans",
      subtitle: "Analiz detaye kontribisyon yo",
      allBranches: "Tout branch yo",
      lastMonths: "dènye mwa",
      totalPeriod: "Total Peryòd",
      currentMonth: "Mwa Sa",
      previousMonth: "Mwa Pase",
      avgDonation: "Resèt Mwayèn",
      perDonation: "pa resèt",
      vsPreviousMonth: "vs mwa pase",
      monthlyTrend: "Evolisyon Mansyèl",
      totalContributions: "Total kontribisyon pa mwa",
      categoryDistribution: "Distribisyon pa Kategori",
      summaryByType: "Rezime pa tip resèt",
      categoryComparison: "Konparezon Kategori pa Mwa",
      donationDistribution: "Distribisyon resèt pa kategori chak mwa",
      detailedSummary: "Rezime Mansyèl Detaye",
      exactFigures: "Chif egzak pa mwa ak kategori",
      month: "Mwa",
      amount: "Montan",
      percentage: "Pousantaj",
    },
    customFields: {
      title: "Chan Pèsonalize",
      subtitle: "Konfigire chan adisyonèl yo",
      addField: "Ajoute yon Chan",
      fieldName: "Non chan",
      fieldLabel: "Etikèt",
      fieldType: "Tip",
      entityType: "Tip antite",
      required: "Obligatwa",
      options: "Opsyon",
    },
    budget: {
      title: "Jesyon Bidjè",
      subtitle: "Planifye ak swiv bidjè anyèl ou yo",
      addBudget: "Ajoute Bidjè",
      budgetName: "Non bidjè",
      fiscalYear: "Ane fiskal",
      plannedAmount: "Montan planifye",
      category: "Kategori",
      totalPlanned: "Total Planifye",
      totalSpent: "Total Depanse",
      remaining: "Rès",
      available: "disponib",
      utilizationRate: "To Itilizasyon",
      expensesApproved: "depans apwouve",
      budgetDetails: "Detay Bidjè",
      noBudgets: "Pa gen bidjè kreye pou ane sa a",
      planned: "Planifye",
      spent: "Depanse",
      progress: "Pwogresyon",
    },
    expense: {
      title: "Jesyon Depans",
      subtitle: "Anrejistre ak apwouve depans yo",
      addExpense: "Ajoute Depans",
      viewExpense: "Detay Depans",
      description: "Deskripsyon",
      vendor: "Benefisyè",
      referenceNumber: "N° Jistifikatif",
      selectCategory: "Chwazi yon kategori",
      totalExpenses: "Total Depans",
      transactions: "tranzaksyon",
      pendingApproval: "Ap Tann Aprobasyon",
      awaitingReview: "ap tann revizyon",
      approved: "Apwouve",
      confirmedExpenses: "depans konfime",
      avgExpense: "Depans Mwayèn",
      perTransaction: "pa tranzaksyon",
      expenseList: "Lis Depans",
      noExpenses: "Pa gen depans anrejistre",
      created: "Depans kreye avèk siksè",
      pending: "An atant",
      rejected: "Rejte",
    },
    bank: {
      title: "Rekonsilyasyon Bank",
      subtitle: "Jere kont yo ak rekonsilye tranzaksyon yo",
      addAccount: "Ajoute Kont",
      accountName: "Non kont",
      accountNumber: "Nimewo kont",
      bankName: "Non bank",
      initialBalance: "Balans inisyal",
      accountCreated: "Kont kreye avèk siksè",
      noAccounts: "Pa gen kont bank kreye",
      transactions: "Tranzaksyon",
      reconciliationStatus: "Estati rekonsilyasyon",
      addTransaction: "Ajoute Tranzaksyon",
      transactionType: "Tip tranzaksyon",
      income: "Antre",
      expense: "Sòti",
      transactionCreated: "Tranzaksyon kreye avèk siksè",
      totalIncome: "Total Antre",
      totalExpense: "Total Sòti",
      reconciled: "Rekonsilye",
      pending: "An atant",
      toReconcile: "Pou Rekonsilye",
      noTransactions: "Pa gen tranzaksyon",
      reconcile: "Rekonsilye",
      unreconcile: "Anile rekonsilyasyon",
      notSpecified: "Pa presize",
    },
    settings: {
      title: "Paramèt",
      language: "Lang",
      theme: "Tèm",
      notifications: "Notifikasyon",
      scannerSettings: "Paramèt eskanè",
      soundEnabled: "Son aktive",
      volume: "Volim",
      successSound: "Son siksè",
      errorSound: "Son erè",
    },
    errors: {
      required: "Chan sa obligatwa",
      invalidEmail: "Imèl envalid",
      passwordMismatch: "Modpas yo pa menm",
      minLength: "Minimòm {min} karaktè",
      serverError: "Erè sèvè",
      notFound: "Pa jwenn",
    },
    layout: {
      members: "Manm",
      finances: "Finans",
      reports: "Rapò",
      communication: "Kominikasyon",
      planning: "Planifikasyon",
      settings: "Paramèt",
      inventory: "Envantè",
      administration: "Administrasyon",
      incomeCategories: "Kategori Resèt",
      expenseCategories: "Kategori Depans",
      salaries: "Salè",
      emailTemplates: "Modèl Imèl",
      churchInfo: "Enfò Legliz",
      inventoryManagement: "Jesyon Envantè",
      churchUsers: "Itilizatè Legliz",
      customization: "Pèsonalizasyon",
      exploreData: "Eksplore Done",
      churchManagement: "Jesyon Legliz",
      adminInvitations: "Envitasyon Admin",
      userManagement: "Jesyon Itilizatè",
      smartInsights: "Entelijan Insights",
      comingSoon: "Byento",
      logoutSuccess: "Ou dekonekte avèk siksè",
      logoutError: "Pwoblèm dekoneksyon",
    },
    superAdmin: {
      dashboardTitle: "Tablo Debò Super Admin",
      dashboardSubtitle: "Apèsi tout legliz sou platfòm nan",
      exportCsv: "Ekspòte CSV",
      manageChurches: "Jere Legliz",
      totalChurches: "Total Legliz",
      registeredChurches: "Legliz anrejistre",
      monthlyRevenue: "Revni Mansyèl",
      recurringRevenue: "Revni rekilye",
      activeUsers: "Itilizatè Aktif",
      approvedUsers: "Itilizatè apwouve",
      activeSubscriptions: "Abònman Aktif",
      inTrial: "nan peryòd esè",
      recentChurches: "Legliz Resan",
      noChurchRegistered: "Pa gen legliz anrejistre",
      quickActions: "Aksyon Rapid",
      exploreChurchData: "Eksplore done legliz",
      userManagement: "Jesyon Itilizatè",
      noDataToExport: "Pa gen done pou ekspòte",
      csvExported: "Ekspòtasyon CSV telechaje",
      // Tenant Management
      tenantManagement: "Jesyon Multi-Tenant",
      tenantManagementDesc: "Jere legliz yo ak abònman yo",
      addChurch: "Ajoute Legliz",
      editChurch: "Modifye Legliz",
      createChurch: "Kreye Legliz",
      saveChanges: "Anrejistre",
      churchName: "Non Legliz",
      slug: "Slug (URL)",
      contactEmail: "Imèl Kontak",
      contactPhone: "Telefòn",
      adminEmail: "Imèl Admin",
      inviteFirstAdmin: "Envite premye administratè a",
      plan: "Plan",
      planBasic: "Bazik",
      planStandard: "Estanda",
      planPremium: "Premyòm",
      planEnterprise: "Antrepriz",
      status: "Estati",
      statusActive: "Aktif",
      statusTrial: "Esè",
      statusSuspended: "Sispann",
      statusCancelled: "Anile",
      trialDuration: "Dire Esè",
      customDate: "Dat Pèsonalize",
      days14: "14 jou",
      month1: "1 mwa",
      months3: "3 mwa",
      months6: "6 mwa",
      year1: "1 ane",
      // Stats
      monthlyRevenueShort: "Revni/mwa",
      active: "Aktif",
      trial: "Esè",
      // Table headers
      church: "Legliz",
      subscription: "Abònman",
      adminStatus: "Admin",
      actions: "Aksyon",
      noAdmin: "Pa gen admin",
      hasAdmin: "Admin konfigire",
      trialExpired: "Esè ekspire",
      trialExpiresIn: "Ekspire nan",
      daysLeft: "jou",
      inviteAdmin: "Envite Admin",
      extendTrial: "Pwolonje esè",
      viewDetails: "Wè Detay",
      deleteChurch: "Efase",
      // Data Viewer
      dataViewerTitle: "Eksplore Done Legliz",
      dataViewerSubtitle: "Vizyon lekti sèlman done legliz yo",
      adminMode: "Mòd Administrasyon",
      readOnlyView: "Ou ap gade done nan mòd lekti sèlman.",
      selectChurch: "Chwazi yon Legliz",
      chooseChurch: "Chwazi yon legliz pou eksplore done li yo",
      selectChurchPlaceholder: "Chwazi yon legliz...",
      membersTab: "Manm",
      donationsTab: "Donasyon",
      eventsTab: "Evènman",
      branchesCount: "Branch",
      dataOf: "Done",
      exploreData: "Eksplore manm, donasyon ak evènman",
      name: "Non",
      email: "Imèl",
      phone: "Telefòn",
      type: "Tip",
      registeredOn: "Enskri nan",
      noMembersFound: "Pa gen manm jwenn",
      amount: "Montan",
      payment: "Peman",
      notes: "Nòt",
      noDonationsFound: "Pa gen donasyon jwenn",
      date: "Dat",
      time: "Lè",
      location: "Kote",
      noEventsFound: "Pa gen evènman jwenn",
      exportMembers: "Ekspòte Manm",
      exportDonations: "Ekspòte Donasyon",
      exportEvents: "Ekspòte Evènman",
      noMembersToExport: "Pa gen manm pou ekspòte",
      noDonationsToExport: "Pa gen donasyon pou ekspòte",
      noEventsToExport: "Pa gen evènman pou ekspòte",
      membersExported: "Ekspòtasyon manm telechaje",
      donationsExported: "Ekspòtasyon donasyon telechaje",
      eventsExported: "Ekspòtasyon evènman telechaje",
      // Extend Trial
      extendTrialTitle: "Pwolonje Esè",
      extendTrialFor: "Pwolonje esè pou",
      currentTrialEnd: "Fen esè aktyèl",
      newTrialEnd: "Nouvo fen esè",
      extending: "Ap pwolonje...",
      confirmExtend: "Konfime",
      trialExtended: "Esè pwolonje jiska",
      // Audit
      auditHistory: "Istwa Odit",
      noAuditLogs: "Pa gen istwa odit",
      trialExtendedAction: "Esè pwolonje",
      // Requests
      pendingRequests: "Demann an Atant",
      // Churches list
      churchesList: "Lis Legliz",
      noChurches: "Pa gen legliz anrejistre",
      // Toasts
      churchCreated: "Legliz kreye avèk siksè",
      churchUpdated: "Legliz modifye avèk siksè",
      churchDeleted: "Legliz efase avèk siksè",
      inviteSent: "Envitasyon voye bay",
      inviteError: "Envitasyon voye men erè voye imèl",
      createError: "Erè lè w ap kreye",
      updateError: "Erè lè w ap modifye",
      deleteError: "Erè lè w ap efase",
      extendError: "Erè lè w ap pwolonje",
    },
  },
};
