// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list_members.ts
import { createClient } from "npm:@supabase/supabase-js@^2.83.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_members_default = defineTool({
  name: "list_members",
  title: "List church members",
  description: "List members of the signed-in user's church. Row-level security limits results to what the user is allowed to see. Supports an optional search term (matches first/last name or email) and a limit.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional search term matched against first name, last name, or email."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("members").select("id, first_name, last_name, email, phone, member_number, status, branch_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search) {
      const like = `%${search}%`;
      query = query.or(`first_name.ilike.${like},last_name.ilike.${like},email.ilike.${like}`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { members: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list_events.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.83.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_events_default = defineTool2({
  name: "list_events",
  title: "List church events",
  description: "List events for the signed-in user's church. Row-level security limits results. Optionally filter to upcoming events only.",
  inputSchema: {
    upcoming_only: z2.boolean().optional().describe("If true, only return events with a start date in the future."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ upcoming_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("events").select("id, title, description, event_date, end_date, location, event_type, status").order("event_date", { ascending: false }).limit(limit ?? 50);
    if (upcoming_only) {
      query = query.gte("event_date", (/* @__PURE__ */ new Date()).toISOString());
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list_donations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.83.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_donations_default = defineTool3({
  name: "list_donations",
  title: "List donations",
  description: "List donations recorded for the signed-in user's church. Row-level security limits results to what the user is allowed to see. Only accessible to roles with finance access (admin, pastor, treasurer).",
  inputSchema: {
    from_date: z3.string().optional().describe("Optional ISO date (YYYY-MM-DD). Only donations on or after this date."),
    to_date: z3.string().optional().describe("Optional ISO date (YYYY-MM-DD). Only donations on or before this date."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("donations").select("id, amount, currency, donation_date, category_id, member_id, payment_method, notes, created_at").order("donation_date", { ascending: false }).limit(limit ?? 50);
    if (from_date) query = query.gte("donation_date", from_date);
    if (to_date) query = query.lte("donation_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((sum, r) => sum + Number(r.amount || 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { donations: data ?? [], count: data?.length ?? 0, total_amount: total }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ihwhbtmnyhhceiwdcfsc";
var mcp_default = defineMcp({
  name: "church-management-pro-mcp",
  title: "Church Management Pro",
  version: "0.1.0",
  instructions: "Read-only tools that let an assistant look up members, events, and donations for the signed-in user's church. All calls run under Supabase RLS as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_members_default, list_events_default, list_donations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
